---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system-add-ons
  namespace: flux-system
spec:
  targetNamespace: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: &app flux-system
  path: ./kubernetes/apps/flux-system/add-ons
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  prune: true
  wait: false
  interval: 10m
