---
apiVersion: v1
kind: Service
metadata:
  name: unraid
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: unraid
  labels:
    kubernetes.io/service-name: unraid
addressType: IPv4
ports:
  - name: http
    appProtocol: http
    protocol: TCP
    port: 80
endpoints:
  - addresses:
      - ${MEDIA_SERVER}
