---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-minio-pv
spec:
  storageClassName: minio
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.16.10.12
    path: "/volume1/minio"
  mountOptions:
    - nfsvers=4.1
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-minio-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: minio
  resources:
    requests:
      storage: 1Mi
