apiVersion: v1
kind: Secret
metadata:
    name: minio
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:UlFi9+I=,iv:8+YfpSYOu/pUF7Wak0Ir2hnWfqcruZHbe8yccnGMSgI=,tag:K3ID5zLcRaQquUWuHQddnw==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:oWLZJ74oozrr6aCY+tzXStnw02h5yNcJ8ym/Msrz1xE9T4QqpJ/LB8Y=,iv:Ya/2V9o4wwomjVLOzH90txg4E0Bd9b54eQT6ikhUXFY=,tag:hKOGGcgyk2x/2itsKv3qUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t8pe6cuxajpqcms5kenlnhh8wmgemr4dnee6eeda07xfsdk2uvtqet3a8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZmJKMmMzR2tQbEdmSTFZ
            amprRVVraTJ1ZXRnZ1ZrUWx4cHJacnlkZTNVCnBVcE04Q3UxZGtzQjlKN3RUbzRU
            YUZ6aUVBT0k4OHQxMlR6d3M5MEZYdFUKLS0tIE1XanZRV1NBbDljb0tmaXRaZ25k
            ZmRzWjJwNDRzWGpaOW5OVG5aMmVha00KARPXqCJnAR2BP8yY40VVYOXQBzN38z5D
            mlYLY3AHZIFBRbC5mV5cgE2VEpudUwHlJGaeUmIX4B6wh7Fsh7vaYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-29T17:37:22Z"
    mac: ENC[AES256_GCM,data:QBAXR+w3Ye6Ceqe6Hmgf/TpiC7TGJlcOh0biGQXNf16So416Zu9mw3FRF/fkIWpmZxFLyZ0j91QNx7pwQFCXeid7/bytOa7I9Ma/a9tanhT8fvZZj7aTBr6pUxYBdsD5uEejqV02Sii9Z/15o0QUfTZEseyB7AHRoukBHL1HTtM=,iv:8v00mZr/+ZNsTbHpGPS2mSIUGScXW+SHdfxXVZjJRrs=,tag:1OBKHiwfPUw0NuOmSPngGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
