---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  name: ${VOLSYNC_CLAIM:-${APP}}
spec:
  accessModes: ["${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"]
  storageClassName: ${VOLSYNC_STORAGECLASS:-longhorn}
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "${APP}-rdst"
  resources:
    requests:
      storage: ${VOLSYNC_CAPACITY:-2Gi}

