---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP}-data
spec:
  accessModes: ["${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"]
  storageClassName: ${VOLSYNC_STORAGECLASS:-longhorn}
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "${APP}-rdst"
  resources:
    requests:
      storage: ${VOLSYNC_CAPACITY:-2Gi}

