apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-secret
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:GrdcO2nLSEDyHfzDB3UP/qOD,iv:LT2l6yPUZ7uiDlRkyvzW5CM8mVGB1GkMQlrF+KtnaJE=,tag:ZtyDSiw2rHIGiEsukZ5y8A==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:rZwJ4H++/xfgLl+a,iv:HBvFrS3uzWdji8X9lpzsoFcZlaavVNeJWgts0URzckU=,tag:MGRrOGr7tWMuLo02E6mvMg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t8pe6cuxajpqcms5kenlnhh8wmgemr4dnee6eeda07xfsdk2uvtqet3a8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtN2NPTTl2QTRkRnpHYldv
            Z2FMckRZNk5WY2NLaTlWaEo2aExsMVY5UWtJCnpOeVFnZXpSbTByQzhMQUdkbVQy
            UlpEVlVQcnlpT2JGVjJtcG5ReFFlSUkKLS0tIHpEYmlBMlR2eWJ4aDZZdHNFNW96
            NWd2VkZtSnZVdjNNNWtaU1RkaXd2TVkKaAu3YYQFO2Ao9fyKQhRIWktbCiMPmA5F
            P9dxN6Xfbb4gGDX3y7HbBes5NuUQ7LUz+s4/r25QT+Ke9hNjrwdZ0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-30T21:19:14Z"
    mac: ENC[AES256_GCM,data:o8/HjiH50uI+U38U0ykBplocO/EWOhU68BykHPOtd0gEfgRvEuR/mMp0ynb6NxNRr0k83qLs2hT1E7Z+I51Qooo0e1QsCJMpU0RjXm537v8qxINvI+aydH5wNoSVnW7f5dHgExfyZpcXAWznOWJhnRSNAUaQI5GOCWpe+7xg9eY=,iv:jYnTe10EWQtp4uLuZOfIBiabwfhQuIUgCgOVZzV4OO0=,tag:U8uRS+jOt0uXgEgq7yV8WQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
