apiVersion: v1
kind: Secret
metadata:
    name: postgres
stringData:
    POSTGRES_SUPER_USER: ENC[AES256_GCM,data:hgGHZsx3u4k=,iv:Z2eoGefQXaJ/7z22LGmDACvdp31LZk+9toTgjv+c9II=,tag:ALwEGSF47uWNRCSaO1VJsw==,type:str]
    POSTGRES_SUPER_PASSWORD: ENC[AES256_GCM,data:0JFfvFDPgSDPtwzWIHaYZ9B4xEezrH/QfqK8vJFTPB6ynzctOXFte2C89Nc555U=,iv:7LHUmknfubWBeDKLcRc0aebgp9XHjo7ib8nng8E5Nng=,tag:hSnV9nxtK+oTGs1XHMGUBA==,type:str]
    username: ENC[AES256_GCM,data:6E0zQBhqXqg=,iv:Xnpyei30RTtyVz4phLZRTHvJci8rSVJTzkV3BLX1q/I=,tag:ulaIzIIAFgQfv79k0uYKJw==,type:str]
    password: ENC[AES256_GCM,data:fqt21yBMI0+JxoEW+LL+fQ9yQJ6CLlWInuUD3SBzgKWAyLg3OYrdBbW1j6gKwtE=,iv:VuiVDjwNe3obsSh98g/Ov3Z7IofiGlsrHXhKIQJksRY=,tag:/zxgzeZpjEOXGCZG6v/iYA==,type:str]
    #ENC[AES256_GCM,data:cNn2oV8BFsvR6GM=,iv:bZBGv1ugukBK3XkyRMHtZDRhsvB+RSvGLtUQPjNYpWI=,tag:opZLrY1M5tEGHHubMT+nQw==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:+JVVapycM4BvU7xqAAdWQ9yL,iv:uXIvJeMYUl0F7X3TTnKGYLy1sRK3YBhUPGBdkckGsdI=,tag:wznqoBcKAhBlHEaqYV4VLQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:4LSjp/c/2IaWx7fYI2dWEMLNJ0AGFw==,iv:PVBYDn72K1K0gDZeLX4Q1UYLPWJsYtEQxjzg1FDuTps=,tag:wZ29iE/5uewiC0eNyV58cA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t8pe6cuxajpqcms5kenlnhh8wmgemr4dnee6eeda07xfsdk2uvtqet3a8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnL1BmWTZOUm1kYnkxWG84
            SzhRNVIxcWdhSEhybUpheFYrKzNWVzlXdUcwCmdac2Z5MTBMTWtzZ2tmUFJycE1x
            NzRhQmJMTi9GRWltdi9uS1AweDI4RTgKLS0tIE8vWlcvdS9Cb3ZDWTJaZzFscGRn
            cEMyd0Y0ZGRLSkkwcWZjeExmdDNhTlUKhSJtjApqWIrwdSphiUllOlWQomQixMH5
            EMWtXd8OoTdyvxPDywItnp2ZWX+8XpsqOanU9F14xHW7lZ24Xy00ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T02:51:30Z"
    mac: ENC[AES256_GCM,data:zmXyyLJqK5lQbPI/1L7oxlxpKDXCL21++huKAIQqkbsX9sChKszT8AltdCpbGG1EZnwSXEFf+HB1bhURk1bXmqbpsZ06+Gqqvpz1n5qAhqG02qZw9HU20LKt1mDWeLyKxxEN4CgySIhF6Z2Uzk2u/VtMyHr0vR8v4pXTP0ZQq3w=,iv:JlDJCY/p+v6SZjJgIU3ZpomjFPtSUKs2wTZEo3Zxftw=,tag:NlN9WGhQKDK0jkn+d5mcdQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
