apiVersion: v1
kind: Secret
metadata:
    name: postgres
stringData:
    POSTGRES_SUPER_USER: ENC[AES256_GCM,data:hgGHZsx3u4k=,iv:Z2eoGefQXaJ/7z22LGmDACvdp31LZk+9toTgjv+c9II=,tag:ALwEGSF47uWNRCSaO1VJsw==,type:str]
    POSTGRES_SUPER_PASSWORD: ENC[AES256_GCM,data:0JFfvFDPgSDPtwzWIHaYZ9B4xEezrH/QfqK8vJFTPB6ynzctOXFte2C89Nc555U=,iv:7LHUmknfubWBeDKLcRc0aebgp9XHjo7ib8nng8E5Nng=,tag:hSnV9nxtK+oTGs1XHMGUBA==,type:str]
    username: ENC[AES256_GCM,data:6E0zQBhqXqg=,iv:Xnpyei30RTtyVz4phLZRTHvJci8rSVJTzkV3BLX1q/I=,tag:ulaIzIIAFgQfv79k0uYKJw==,type:str]
    password: ENC[AES256_GCM,data:fqt21yBMI0+JxoEW+LL+fQ9yQJ6CLlWInuUD3SBzgKWAyLg3OYrdBbW1j6gKwtE=,iv:VuiVDjwNe3obsSh98g/Ov3Z7IofiGlsrHXhKIQJksRY=,tag:/zxgzeZpjEOXGCZG6v/iYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t8pe6cuxajpqcms5kenlnhh8wmgemr4dnee6eeda07xfsdk2uvtqet3a8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnL1BmWTZOUm1kYnkxWG84
            SzhRNVIxcWdhSEhybUpheFYrKzNWVzlXdUcwCmdac2Z5MTBMTWtzZ2tmUFJycE1x
            NzRhQmJMTi9GRWltdi9uS1AweDI4RTgKLS0tIE8vWlcvdS9Cb3ZDWTJaZzFscGRn
            cEMyd0Y0ZGRLSkkwcWZjeExmdDNhTlUKhSJtjApqWIrwdSphiUllOlWQomQixMH5
            EMWtXd8OoTdyvxPDywItnp2ZWX+8XpsqOanU9F14xHW7lZ24Xy00ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-30T00:17:15Z"
    mac: ENC[AES256_GCM,data:QybpX6tWnhUr1I4nAWYf7ciEHj0wd8FU/EdYQvmlWTzDRaGzHgqcUBZJ4KmT6RiRv9IvfB5+627TojrGO6rQVw63klQ660wqM/ppJwYwYMGJnwDM2/uJGmjn+9mS16eCm/L3oD71XS/uxWyAretA2Il0Qn6oYWC9wdxlZuMoIHM=,iv:D1EAVkstNwtbItb3bhxKxNM4bbTbXYSqNG5WjsWAX1o=,tag:8H8lfKLd1GO1L5e2X7HisQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
