# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: it-tools
spec:
    chart:
        spec:
            chart: app-template
            sourceRef:
                kind: HelmRepository
                name: bjw-s
            version: 3.5.1
    interval: 1h0m
    install:
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            strategy: rollback
            retries: 3
    values:
        controllers:
            it-tools:
                replicas: 1
                strategy: RollingUpdate
                annotations:
                    reloader.stakater.com/auto: "true"
                pod:
                    securityContext:
                        runAsUser: 1000
                        runAsGroup: 1000
                        fsGroup: 1000
                        fsGroupChangePolicy: OnRootMismatch
                containers:
                    app:
                        image:
                            repository: ghcr.io/bjw-s-labs/it-tools
                            tag: 2024.5.13
                        resources:
                            requests:
                                cpu: 5m
                                memory: 32Mi
                            limits:
                                memory: 256Mi
                        securityContext:
                            allowPrivilegeEscalation: false
                            capabilities:
                                drop:
                                    - ALL
                            readOnlyRootFilesystem: true
        service:
            app:
                controller: it-tools
                ports:
                    http:
                        port: 8080
        ingress:
            app:
                className: traefik-internal
                hosts:
                    - host: ENC[AES256_GCM,data:RhV7wUNtEB4CieG52EAfPBMmYkU=,iv:LTBjSWLMZhPLngl8N/NAWj+tZRWE5nExUjtEN2cIy1c=,tag:RrfrMLXW6VeJZB8vpOIiZw==,type:str]
                      paths:
                        - path: /
                          service:
                            identifier: app
                            port: http
        persistence:
            tmp:
                type: emptyDir
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNjREU0V6TUFKZitXNm9T
            TldJTjk1dDZKa2ltL0pubXFxUVkway9XV0g0ClZ4NHR2RW1CRCtqU2JGN3FLd0dw
            ZFBWVU4zUlI3YXJLdkFhL0pSYmNjMnMKLS0tIFVEanN2UVdkbUJWazNFM0NYTmxR
            UWhXRERxam1oWThEN3ozMllycHFFYzQKV7eqOqAYeRtPmmx2OZ/91/B3M+jkpq3W
            I6QsktfjwTKpsswal1+Zhbj7AMWBMLVJiUVLJLbUtLNHOREl0LElow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-20T04:11:27Z"
    mac: ENC[AES256_GCM,data:JyZjRSJFJmvaWVCXKyM5Yv1TPvTGR8EsqmdaUrWgmYMWjZPwMpopSCVEaDVmGz59AJA6q0BYgBe+oVd1T9lApkk99bhOF2GTPY+vDkwU5T7aPsmiEWsrvbsP6RNwgY9/H7E4WoVv7q7LC+nSfFRirxAvUt+/Rfn/AE5NhwN/a54=,iv:9Su0zNY9JvHnN37uYFGSy4cdBCteivRLcASMDCA1SL4=,tag:nnow/xVL7lRYRM3CKeLxVA==,type:str]
    pgp: []
    encrypted_regex: ^(host)$
    version: 3.9.1
