apiVersion: v1
kind: Secret
metadata:
  name: overseerr-restic
stringData:
  RESTIC_REPOSITORY: ${VOLSYNC_RESTIC_REPOSITORY}/overseerr
  RESTIC_PASSWORD: ${VOLSYNC_RESTIC_PASSWORD}
  AWS_ACCESS_KEY_ID: ${VOLSYNC_B2_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${VOLSYNC_B2_KEY_SECRET}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr
spec:
  accessModes: ["ReadWriteOnce"]
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: overseerr
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: overseerr
spec:
  trigger:
    manual: restore-once
  restic:
    repository: overseerr-restic-secret
    copyMethod: Snapshot
    accessModes: ["ReadWriteOnce"]
    storageClassName: longhorn
    volumeSnapshotClassName: longhorn-snapshot
    cacheAccessModes: ["ReadWriteOnce"]
    cacheCapacity: 8Gi
    cacheStorageClassName: longhorn
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    capacity: 2Gi # must match the PersistentVolumeClaim `.resources.requests.storage` size above
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: overseerr
spec:
  sourcePVC: overseerr
  trigger:
    schedule: "15 */8 * * *"
  restic:
    pruneIntervalDays: 7
    repository: overseerr-restic-secret
    copyMethod: Snapshot
    accessModes: ["ReadWriteOnce"]
    storageClassName: longhorn
    volumeSnapshotClassName: longhorn-snapshot
    cacheAccessModes: ["ReadWriteOnce"]
    cacheCapacity: 8Gi
    cacheStorageClassName: longhorn
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      hourly: 24
      daily: 7
      weekly: 5
