apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secrets
stringData:
    slack_url: ENC[AES256_GCM,data:JpyGurOxQYs5tGywNkHSpfkBg0cdvw+650QLzDgIUJ/RywwJkaoH/EJXKLG0wr3wbrPP4t0MlH7aY4ioLFDkFojCCg3LbgOBMEEgBG6MHzvk,iv:kAj2Vgm9F95R1zRj6n5LaFUjasHmSpytdUb2AeqFygY=,tag:PyDOjCEisgkziJPIPpQcGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMzRRSnRiVVZnQ2g4bndz
            OVdpb2prbVF6UVhvTVVubmVmR3hZUWRMWEhnCkozOFdlaUl0TFJuM3JYcXRjejFF
            QzFTZGtYaDJydHlGbVhCVjhJcVpkQlkKLS0tIGdLbFVpOGJlNDgxZ3E4MUJIMDNZ
            UFUwVXBmUTdmeWZTcHJnL3VWOUk0SUUKYVIImfxBDVKBmANeRhYm4SOSn4+S9r2J
            cT1QWKtBhB/t22oJLvas7JvnxVFFyw+VFUQUqa8CRCaMz7ZKc8gAJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T00:01:18Z"
    mac: ENC[AES256_GCM,data:m+Vlpx8sw+pOZjBuXJtryDkPlX8e3/giy8QuunoKjLnd1L2NM0F9XZ5vwoxqILN3L5QtTHrRqMSd7OynnQoXEK/I7sQDf/tsqt0QwqXPghL1C7z6LD5/ldrzA/2qKRnqQTHW5WHfYb7xPC5f1UD6iOo0HzeHfHluzpgx5XpkpGc=,iv:fCdR5TBifY4xeRTTa2FEbe0b4uNNAPz3mkoMtDEz0QY=,tag:0a2IbTjyxI6xye99PAQQSg==,type:str]
    pgp: []
    encrypted_regex: ^(slack_url)$
    version: 3.9.1
