apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
stringData:
    slack_url: ENC[AES256_GCM,data:bSpW8KxQ4f79isbjyPSoVZ6EJednxrvufDl5yeixuJvafWQ1Ut501CvoDwfd16hcF2vOaEoqHtGzkTV67N17cF2YcyNUEcdoy6YY8IV+1yi1,iv:aNB3Q3uow7jmFKQjVHMc+TUchRrhvpViQ0jU+ggL5kU=,tag:ocVTrPu+Z38GYn6xog09vw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlYVkwTldkMnN6aW1neEtN
            TmpMSkRlZDMrY0hnc2RoWFFQS1hWeU90Z2hjClQwbTQxTG4xTGdxaGwwY2NKSUJV
            UXZWNTlhK0laV05zWFBuaVRDRGZaQU0KLS0tIFBMRDV1d0FNUlhCTmZtMktKUGI3
            MGRBUHFYZXlOczRybEtNanZFbGdWS2cK0Xk7vFfyxFbrh9bdmq6mymrqIUzUwvmT
            XXzy9XeH9sB5D0aUvTvIavJw4FqDzR1XF0oJHro4E76w3rrnNvUYBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-24T04:38:12Z"
    mac: ENC[AES256_GCM,data:yeC1CQ7dlXTFTXP7cuCLCxttmuVPjC5xS23VzhJb9TentfACLJ8ZauO4CCwOeeUp6YtBN7mVHNra+Ddqy6S01WGF09qKinCIBeXatBSNaOgOJ+ykZBznMlwNVPluYxPaDCL05FnWwguDDlOHujWALWqXY8DnQ7tsdPUwgc+h27Y=,iv:O6hFX8XSZvPxMAZP/ucqr96jR0lVjS54aMBBZCa6oNE=,tag:+HyhPO5lweTTaBQhONwekw==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.1
