apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secrets
stringData:
    slack_url: ENC[AES256_GCM,data:bSpW8KxQ4f79isbjyPSoVZ6EJednxrvufDl5yeixuJvafWQ1Ut501CvoDwfd16hcF2vOaEoqHtGzkTV67N17cF2YcyNUEcdoy6YY8IV+1yi1,iv:aNB3Q3uow7jmFKQjVHMc+TUchRrhvpViQ0jU+ggL5kU=,tag:ocVTrPu+Z38GYn6xog09vw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlYVkwTldkMnN6aW1neEtN
            TmpMSkRlZDMrY0hnc2RoWFFQS1hWeU90Z2hjClQwbTQxTG4xTGdxaGwwY2NKSUJV
            UXZWNTlhK0laV05zWFBuaVRDRGZaQU0KLS0tIFBMRDV1d0FNUlhCTmZtMktKUGI3
            MGRBUHFYZXlOczRybEtNanZFbGdWS2cK0Xk7vFfyxFbrh9bdmq6mymrqIUzUwvmT
            XXzy9XeH9sB5D0aUvTvIavJw4FqDzR1XF0oJHro4E76w3rrnNvUYBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-24T04:28:39Z"
    mac: ENC[AES256_GCM,data:1PxVmxBqmwML+89//4y5XnYDqi0EJzVyvkFo+VX9xMiJDavQEYqPAHDH7Zh6OsO06vKPZnwtnK0hnVutxPduP0uE5kXpTnJpZ0hNUNiuhed0XSXPhmGGSVlqWNUp8wW/y8XgZuFMFKnkMuQ3jZFscVVTjbfLNx2ooI3TKjPWvPw=,iv:rHBfvJcV54NZ6plaIrJJ97ZZvwYyG/p+GzWx+jBqSmY=,tag:sXQDlo/MlV6WSUWTHifUxg==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.1
