apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:pG0q1hPftHChM/u5N8IVDjuAWW6VT1hti80ngIsQL+fMUsIL8wGvik2VMFnXTJtSzhRwim0=,iv:4AWudMO51mi0XzPlduHZBaHRMJ9VDUJ+UpBJOwYNSCQ=,tag:hDNwVl6W4b5Fj3a9nGxCFg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUVorS01TWU91ZDlZdlRp
        YUZtb1Q5RjhGYm5lRU00RWw0ZElsaU1sV0RFCmVMdkNrV1FkeWpKd1VaTFp4eUFG
        WW5IbjZyQ2RnSllJdWo3bzYxZmtpcFkKLS0tICtTd3V5Z3pSb1NmYWpQSzJsb2ZU
        NjUxcFFxR3ZGNUI3QW5oczZBTzVhTE0KtQ4COEIcRO9iRvYZno4tT6+gWhHlIJtO
        0x+qxPkmYM6z3AO84t3iwZtNY047vZ7r1ujTid/zXj3K0+U9yKjZjw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12s85l6vmg08smu66rskhpaupg7htdzdvdrj0ca6rzwn3ujneaq9q7nzaxn
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VWpUWEppVzZxTmlraWNF
        bUU3UEZJTWpkY2hKc01MNm9Kb2pTQ3hiUkJVCjhwRUZiSlJIWnlROU9mTWpnVURK
        ZWhUNWd6c1dKclczcXBJbGtiUlY1cjQKLS0tIFdGRkN2R0xsTnJBc3VWVWFDSlcv
        dHVBYlBhUUtUSnNYK2lmQXZMUHRkeVkKnprww32hoZXdpCItj5Syaacc8PgCHGpX
        ozTKdU56crrZhtRP4QXytri3Pv6OPvqSm1s6yrJm0FF217TlDMt+kA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pdy90y7mk4equuwna3eecgl00d8l2max769ym98g54m3lmxjepus5ydsd8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-28T22:14:39Z"
  mac: ENC[AES256_GCM,data:9NJ7JCFu9cg/sEr0UaTTHWQrBvmE7oOfGr+hgH5Qk4553Ft/m8PgWyVy1wTu+P5JTy2RHvZmUxn5gle+Jv46Neye17At5nBTa3/OyfWrBlNlLAYb8jqUwYFzieg3cWd6Z03bp3KqV9L6BnZFV12t6UFBzDqhhNNW283nnMsiH5g=,iv:m3v9hNTuBMSaFJi4il1lC29IX/5JZugS7+ufCEeDvuQ=,tag:zCMt9CND1VV1RvFsWP5tHw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
