apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secret
type: Opaque
stringData:
    cloudflare-token: ENC[AES256_GCM,data:1qu18qegZayHbUKHhLkjt6dM/gvP0uGF78CjuMaY/4zh04mH7dzzaA==,iv:sE92WP38pqzLJnvSLHtqehT4WJpKXDEEIpprgR9hdCk=,tag:zQzthetBFdYdS2289AUHzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRN094Z2ZHeDM0TDFuendN
            OUY2YVlnZ1pKOW5NMThsaytHUjUwa2Y5aXhZCkVEeTVUN1UvQ3hDT3p0Z0hhTDFP
            YURzRXhmcEpqOEFsaWtFdTBiQ2RpVmMKLS0tIEI5bjFhWWpYVUlNOTUwODF2Qm56
            cGNObThXVHZNVTJCWHJ3bkkzbHdIWWcKIZy8u0R1JZ9InmTNbSYQPeTKitxBHDOO
            VXMUIfarU0xG6W3q2MRsF+x+w7+Z4COK4TNbLOkfbNcB+1XknEl5FA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T06:32:25Z"
    mac: ENC[AES256_GCM,data:iqiDDPBX2hROwgLj9Mb2LgsH4B+Zk21x5Qu61zMq6x+LALk4N+P2JjuXZlFtW9IlHCxeUJ+b940QstLzAgR/DDyakji262CtRZVHuJS13r+5vDDrcIlwKeyqbgcIP28i8t0Q+WBZ2p+ao9PwSdL4XDfJYFehJPttr91LJGGZ8DQ=,iv:07483IyiL8+CJ+P4xr4gOti1IxaUhpvFDnOvPZaO9Pk=,tag:QbKy7b+NECWqZU1WMNAzzw==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.1
