apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secret
type: Opaque
stringData:
    cloudflare-token: ENC[AES256_GCM,data:t8akZNNgiz+whRFNcwnBkIC0pWIccJMbzoVrycww2ROkdXRdMfOmrQ==,iv:YGIzfkj0jh79AbDalkiBGQhpAoE62R6Gd89u1PFBTnQ=,tag:QM0V8cN+Bl51MXQcplbN7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRN094Z2ZHeDM0TDFuendN
            OUY2YVlnZ1pKOW5NMThsaytHUjUwa2Y5aXhZCkVEeTVUN1UvQ3hDT3p0Z0hhTDFP
            YURzRXhmcEpqOEFsaWtFdTBiQ2RpVmMKLS0tIEI5bjFhWWpYVUlNOTUwODF2Qm56
            cGNObThXVHZNVTJCWHJ3bkkzbHdIWWcKIZy8u0R1JZ9InmTNbSYQPeTKitxBHDOO
            VXMUIfarU0xG6W3q2MRsF+x+w7+Z4COK4TNbLOkfbNcB+1XknEl5FA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T06:17:59Z"
    mac: ENC[AES256_GCM,data:RCkVhlsazLK7q/4XRJkOM+BdKux//0cEso11tywGG89Avt+MVV5mLvrwmiBWitBr5Yv1Y60599L2Pijg4avejJIdpW7zrc5Ec3oVPmTp/3kcrb6biSY2yg4sojxnz4Xs0cWHmpBVNRXT6fxjxIjcr2jxtngD6sfNtNU+Y4lis9E=,iv:6ytT2yL0SrnAog8x8d7XdfHxUprm/y07gfrvGMALtBE=,tag:EqLexbG86UZGuRMXbGt6ww==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.1
