apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secret
type: Opaque
stringData:
    CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:FOjwEY9ld5/CpbQrb8ZSivUlyQi+7mE6zSGObKjePkJkj07aFuWpUg==,iv:oiU25TUhzGnljv55Axi53/JpU8EnvGDLcFdDThfuwTM=,tag:dL8rEsQW9q6dvnmjhBDEjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRN094Z2ZHeDM0TDFuendN
            OUY2YVlnZ1pKOW5NMThsaytHUjUwa2Y5aXhZCkVEeTVUN1UvQ3hDT3p0Z0hhTDFP
            YURzRXhmcEpqOEFsaWtFdTBiQ2RpVmMKLS0tIEI5bjFhWWpYVUlNOTUwODF2Qm56
            cGNObThXVHZNVTJCWHJ3bkkzbHdIWWcKIZy8u0R1JZ9InmTNbSYQPeTKitxBHDOO
            VXMUIfarU0xG6W3q2MRsF+x+w7+Z4COK4TNbLOkfbNcB+1XknEl5FA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T00:45:15Z"
    mac: ENC[AES256_GCM,data:IXLG7Q/w2knbI3g38VxCNpHQarinBOQ8/HaIB1eVNK6ORXBOdlHrDCu71Ya2iRKCYRCpg2AZ/ctSbKlYDvIWdxtES3zzF0XI2NKN6To1e9Uy0dzx9FNVv9TYP9Y8mPVNv/MuFdQxg8+nmlycIQCPgdF0z4Cgd9KBU+BEUq6+uF4=,iv:5OI/zYu27GV23Uz4OJpbIrtPXEBGd2e/oDmy1yB6g0E=,tag:d79xshVexD0dIzszwMyBgw==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.1
