---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grampsweb
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: grampsweb-secret
    template:
      data:
        GRAMPSWEB_SECRET_KEY: "{{ .SECRET_KEY }}"
        GRAMPSWEB_OIDC_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        GRAMPSWEB_OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
        GRAMPSWEB_EMAIL_HOST: "{{ .SMTP_HOST }}"
        GRAMPSWEB_EMAIL_PORT: "{{ .SMTP_PORT }}"
        GRAMPSWEB_EMAIL_HOST_USER: "{{ .SMTP_USERNAME }}"
        GRAMPSWEB_EMAIL_HOST_PASSWORD: "{{ .SMTP_PASSWORD }}"
        GRAMPSWEB_DEFAULT_FROM_EMAIL: "{{ .SMTP_FROM }}"
  dataFrom:
    - extract:
        key: grampsweb
    - extract:
        key: smtp
