---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app grampsweb
spec:
  chartRef:
    kind: OCIRepository
    name: grampsweb
  interval: 30m
  values:
    controllers:
      grampsweb:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image: &image
              repository: ghcr.io/gramps-project/grampsweb
              tag: 26.9.1@sha256:ac4db1ba963f5d2604e6b9a34be50c5a2c37271699f5a6df93c9492ecc8870e5
            env: &env
              TZ: America/Los_Angeles
              GUNICORN_NUM_WORKERS: 2
              GRAMPSWEB_TREE: 2fff588f-1d54-471d-b665-5986760e6b1c
              GRAMPSWEB_REGISTRATION_DISABLED: "true"
              GRAMPSWEB_MEDIA_PREFIX_TREE: "true"
              GRAMPSWEB_NEW_DB_BACKEND: sharedpostgresql
              GRAMPSWEB_POSTGRES_HOST:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-db-app"
                    key: host
              GRAMPSWEB_POSTGRES_PORT:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-db-app"
                    key: port
              GRAMPSWEB_POSTGRES_USER:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-db-app"
                    key: user
              GRAMPSWEB_POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-db-app"
                    key: password
              GRAMPSWEB_SEARCH_INDEX_DB_URI:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-db-app"
                    key: fqdn-uri
              GRAMPSWEB_USER_DB_URI:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-db-app"
                    key: fqdn-uri
              GRAMPSWEB_BASE_URL: https://gramps.${SECRET_DOMAIN}
              GRAMPSWEB_OIDC_ENABLED: "true"
              GRAMPSWEB_OIDC_NAME: Xtm ID
              GRAMPSWEB_OIDC_ISSUER: https://sso.${SECRET_DOMAIN}
              GRAMPSWEB_EMAIL_USE_SSL: "false"
              GRAMPSWEB_EMAIL_USE_STARTTLS: "true"
              GRAMPSWEB_CELERY_CONFIG__broker_url: redis://{{ .Release.Name }}-dragonfly.selfhosted.svc.cluster.local:6379/0
              GRAMPSWEB_CELERY_CONFIG__result_backend: redis://{{ .Release.Name }}-dragonfly.selfhosted.svc.cluster.local:6379/0
              GRAMPSWEB_RATELIMIT_STORAGE_URI: redis://{{ .Release.Name }}-dragonfly.selfhosted.svc.cluster.local:6379/1
            envFrom: &envFrom
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 1Gi
          celery:
            image: *image
            args:
              - celery
              - -A
              - gramps_webapi.celery
              - worker
              - --loglevel=INFO
              - --concurrency=2
            env: *env
            envFrom: *envFrom
            resources:
              requests:
                cpu: 25m
                memory: 256Mi
              limits:
                memory: 1Gi
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 5000
    route:
      app:
        hostnames: ["gramps.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /app/users
            subPath: users
          - path: /app/indexdir
            subPath: indexdir
          - path: /app/secret
            subPath: secret
          - path: /root/.gramps/grampsdb
            subPath: grampsdb
          - path: /app/media
            subPath: media
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
      cache:
        type: emptyDir
        globalMounts:
          - path: /app/thumbnail_cache
            subPath: thumbnail_cache
          - path: /app/cache
            subPath: cache
