---
alerting:
  slack:
    webhook-url: ${SLACK_WEBHOOK_URL}
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

web:
  port: ${WEB_PORT}
storage:
  type: postgres
  path: postgres://${INIT_POSTGRES_USER}:${INIT_POSTGRES_PASS}@${INIT_POSTGRES_HOST}:5432/${INIT_POSTGRES_DBNAME}?sslmode=disable
  caching: true
metrics: true
debug: false
ui:
  title: Status | Gatus
  header: Status

endpoints:
  - name: Status
    group: external
    url: https://status.${SECRET_DOMAIN}
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: slack
        send-on-resolved: true

  - name: Flux webhook
    group: Services
    url: https://flux-webhook.${SECRET_DOMAIN}
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 404"
    alerts:
      - type: slack
        send-on-resolved: true

  - name: Minio
    group: Services
    url: https://minio.${SECRET_DOMAIN}/minio/health/live
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: slack
        send-on-resolved: true
