---
web:
  port: ${WEB_PORT}
storage:
  type: postgres
  path: postgres://${INIT_POSTGRES_USER}:${INIT_POSTGRES_PASS}@${INIT_POSTGRES_HOST}:5432/${INIT_POSTGRES_DBNAME}?sslmode=disable
  caching: true
metrics: true
debug: false
ui:
  title: Health Status
  header: Health Status
alerting:
  slack:
    webhook-url: ${SLACK_WEBHOOK_URL}
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m
endpoints:
  - name: gatus-status
    group: external
    url: https://status.${SECRET_DOMAIN}
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"
      - '[RESPONSE_TIME] < 300'
    alerts:
      - type: slack
        description: "healthcheck failed 3 times in a row"
        send-on-resolved: true
      - type: slack
        failure-threshold: 5
        description: "healthcheck failed 5 times in a row"
        send-on-resolved: true
