---
web:
  port: ${WEB_PORT}
storage:
  type: postgres
  path: postgres://${INIT_POSTGRES_USER}:${INIT_POSTGRES_PASS}@${INIT_POSTGRES_HOST}:5432/${INIT_POSTGRES_DBNAME}?sslmode=disable
  caching: true
metrics: true
debug: false
ui:
  title: Health Status
  header: Health Status
alerting:
  slack:
    webhook-url: ${SLACK_WEBHOOK_URL}
    default-alert:
      description: health-check failed
      send-on-resolved: true
      failure-threshold: 3
      success-threshold: 3
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m
endpoints:
  - name: status
    group: external
    url: https://status.${SECRET_DOMAIN}
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions: ["[STATUS] == 200"]
    alerts: [{ type: slack }]
  - name: flux-webhook
    group: external
    url: https://flux-webhook.${SECRET_DOMAIN}
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions: ["[STATUS] == 404"]
    alerts: [{ type: slack }]
remote:
  instances:
    - endpoint-prefix: ""
      url: "https://status-utility.${SECRET_DOMAIN}/api/v1/endpoints/statuses"
