apiVersion: v1
kind: Secret
metadata:
    name: slack-bot-url
stringData:
    address: ENC[AES256_GCM,data:UY8KTKDRjBWKrl3UR+VqaqpcEWr4PS9o5fgkgwdQwLkUAzOagWFfItayMILSq7VgFS+zub4BY9oo3qXJehNY3K0aSfPeFjJEUceuEMW1Wawi,iv:NbiwAFR3ENCkqGne0kZ6LSE9GTfAbNyhaIE0QloS3rs=,tag:HgJyAC+Ce89QXwZz/G1I8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t8pe6cuxajpqcms5kenlnhh8wmgemr4dnee6eeda07xfsdk2uvtqet3a8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5K1o3OG96TTdDU3lrMTRn
            RkRpV1FUOVJFWkVKd0ZnL2pWMnYxRnFuZDBNCkNTeEwxY3JkTlZ2TG4wSHFPNFZw
            c0k3SVVEenBlQmE1OXovZklYWm1IbmsKLS0tIENsZnFxWU0vaGhkMldlWWd5MVl5
            TWEzR2dvNG93VXRWRzEyV2FpUGQzczgKWjaRTYaZhfTUdWofFQP3badd3fkcZ9dd
            tr/w3jeJw3Hcne9hkbxZoIOxtzPQYa01ddleGj0u7P0E2bgK7D+Rmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-07T06:46:39Z"
    mac: ENC[AES256_GCM,data:7BKczeblBqSFsWPUpibgG6cJ0ywUvQ9nUmUfA+KQnJrDxkugh/5wfBbCIeLsTmKixY3nA5B+IhuPjjnPXt/FUvo0j/zG2cl8TG4aHnIQlvq8Hz1/3yh6uGxi1MIHMUlR2Z71f85KAdn/REv14tpbE3xZMNhgPBDpapjxkclCQ5Y=,iv:wKL2Nl2GkKigkM2/IEzSHugGHtj/FAGk8Nu4k1/JdaQ=,tag:kk3GaluBoW+zUYy6eEgfag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
