apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:kYUA1j2RWY0UphonxCVSyF5DGsylCj4LLufyy8vujSM=,iv:reHqUw+5w6NtS4+87zvlFjzqYjZvrNIrIf/5Uu4sJD0=,tag:py1WY5cn+wngddfQCSMYhQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCOHNITWJIbWJXQ3g5czI5
        aWdxSnljMEt5VW40cCtWc0lSVDVNblhMUEQ4CmgrMjN5WDF4ODJad3VQWVU2RUp4
        bG10VitLY1Y2enhURlFyYTVoQzZEZlEKLS0tIEdMZDFGcEk5dFZHZFcwYkV0Z1hq
        bmpURkFLbVZFb1ZUSTBVS0NLeDluVHMKqfvaJpRS4vNOenLr3sOmqE98faPt9m6K
        TO4lVaJhyP+5XHkqfG6FJxDOAwUK8LnGiez48E7yt1ulQlcju5S4EQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12s85l6vmg08smu66rskhpaupg7htdzdvdrj0ca6rzwn3ujneaq9q7nzaxn
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUVQ4OFg0NnNiYjJRb01y
        KzVDd1A3dk9GMUtBbm1OUkdxbm1SMGpOYjFzClJoN3lLVEUydGh3UDQrcVJnODYv
        TVdJanQxaEhJY2x1a245R1l1ZkhrRTgKLS0tIHVSWUpUMk9ZUHBDOXlUMUhqWndq
        eXQrQnJSQUhneEtyQXZBRUgwRTZsNFUKRzrOAGUvb09158PzO3bnrARJ41Sx7YRG
        yJDONOSWwfmVWXPtjm2Iwv8/lSsCQqOkJmGCtRSAlm2X03ObeSrQpQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pdy90y7mk4equuwna3eecgl00d8l2max769ym98g54m3lmxjepus5ydsd8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-02-21T05:14:17Z"
  mac: ENC[AES256_GCM,data:Ic45qHNq/G6DW+uQ1ufoCuXvlN0msG+4v01tMYuOdz9vZQcAm8I/2cieMR6wNjs/1LZ7KX79MGJgwSE/hoC1DZvfL96p4aUliMJazTPwASFpEjfEnOc4SpMoLKBOqnoGW4XyRu9aQC4mXvy46HhS8SLIM0g/vu9GsYWTWeygclA=,iv:Hy/vsBargiAZV59DH9y19iwcCIvMR1bfxpDShFqY1iI=,tag:gLsqxsnvPoVNE4h06llSBg==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
