# traefik.containo.us/v1alpha1 depreciated in Traefik v3
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
    name: auth-headers
spec:
    headers:
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        referrerPolicy: no-referrer
        contentSecurityPolicy: 'default-src ''none''; script-src ''self'' ''unsafe-inline'' ''unsafe-eval'' https:; style-src ''self'' ''unsafe-inline'' https:; img-src ''self'' data: https:; font-src ''self'' https: data:; connect-src ''self'' https:; frame-src ''self'' https:; media-src ''self'' https:; object-src ''none''; frame-ancestors ''self''; base-uri ''self''; form-action ''self'';'
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
            X-Forwarded-Proto: https
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcDRIR1d5RGFrbUtuZ2Jw
            UVpvWlFtY2ZwdWM2VkwwNVEwcFFZSCthQUhRCmlaZlEreHpTejc4NTNMS1RSdkEx
            R0RGQ3lUU09hLzQyQzgvT2VEN01rT0EKLS0tIHQ4THZFNzA1OTVMT0JPbkJib3M4
            WTNyMzByMERjT3FYVyt2eTljM3NJcGsKJXZau5Ef5iNZqu28ztpieW/YJ4uIpdXO
            8eBBEoU+Y3vxIAcS02UxlPG2rBOLOjVufhvxdQrnCf0V07E54JS4bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T16:57:58Z"
    mac: ENC[AES256_GCM,data:4r02Brdc9A2UUmdCGLrLC9NAMaHgSapV0zDL6vIRyvTCTwoRMj4cWzBIp1mwr39omXcuCubVYJABkBYBzAa7DT8xKMzoVs/S2+vGTdo20g1BrEtXM1xH1r2XHASqBQrf+Hzmu3GtWMD6T3WpNJR/nbccyViUCZhXizpCBFojcD0=,iv:pocd7C/5mwpvvliw4drKoKHW8y/316QcgVdQToGURI0=,tag:jb4OCdScn6Wmh5UhBzZz7w==,type:str]
    pgp: []
    encrypted_regex: ^(match)$
    version: 3.9.1
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
    name: lldap-dashboard
    annotations:
        kubernetes.io/ingress.class: traefik-internal
spec:
    entryPoints:
        - websecure
    routes:
        - match: ENC[AES256_GCM,data:MwDrA8cETxwrL/fGl0G3WOJh2kAOd3Cf0o74jJQllHv04g==,iv:CjtXFT5nIjGA5FMvpKEoUQwYsJoF7uYoin6U+FI4RXo=,tag:/NF8Xh4l6eDhsDK16IFR8g==,type:str]
          kind: Rule
          services:
            - name: lldap-http
              port: 17170
          middlewares:
            - name: auth-headers
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcDRIR1d5RGFrbUtuZ2Jw
            UVpvWlFtY2ZwdWM2VkwwNVEwcFFZSCthQUhRCmlaZlEreHpTejc4NTNMS1RSdkEx
            R0RGQ3lUU09hLzQyQzgvT2VEN01rT0EKLS0tIHQ4THZFNzA1OTVMT0JPbkJib3M4
            WTNyMzByMERjT3FYVyt2eTljM3NJcGsKJXZau5Ef5iNZqu28ztpieW/YJ4uIpdXO
            8eBBEoU+Y3vxIAcS02UxlPG2rBOLOjVufhvxdQrnCf0V07E54JS4bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T16:57:58Z"
    mac: ENC[AES256_GCM,data:4r02Brdc9A2UUmdCGLrLC9NAMaHgSapV0zDL6vIRyvTCTwoRMj4cWzBIp1mwr39omXcuCubVYJABkBYBzAa7DT8xKMzoVs/S2+vGTdo20g1BrEtXM1xH1r2XHASqBQrf+Hzmu3GtWMD6T3WpNJR/nbccyViUCZhXizpCBFojcD0=,iv:pocd7C/5mwpvvliw4drKoKHW8y/316QcgVdQToGURI0=,tag:jb4OCdScn6Wmh5UhBzZz7w==,type:str]
    pgp: []
    encrypted_regex: ^(match)$
    version: 3.9.1
