apiVersion: v1
kind: Secret
metadata:
    name: lldap-secret
stringData:
    #ENC[AES256_GCM,data:R7MCxA==,iv:R2N1Ydb6M+EFr/nTXqW9GAgsnoA+32x4pqoSEV9iwBI=,tag:lvDNcI/mGM+i025S67z7og==,type:comment]
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:75FRHPD9aAZtrb1X8V46p4riyLusk0KTbjyJ8Vt3+bDC4Ye7Q8/5Kn/L31zVdPcmMP9zirTV/VX0YBC6L/XqbgYDrA+s2q3mo2MIiigCYO78qc8f5g==,iv:Py81NcldT70sIbjzvgmH1gRtk4N2Ws3nkjk+o5xbVIY=,tag:hfJWYIa8XZzlrbw2Z+hnsw==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:G9+h0BCNYGYn6ie6AyixDGUVpApRgMQV9d+McCVdi2vx04Q=,iv:eIQo9dv4NNoaAhVFilBWVYlzLuVbIYrnxHSMq2rtrNw=,tag:Uul0h2OAUEAXCbP0Do0epA==,type:str]
    LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:ENWahmqnO3Jwn24NeBBAt42tyJHUYG6IAXPMw8CMwc3PrFN4igoZyG9DmZknU7q7qc86x7vSIwGq/TVJFsikxQ06cgDackGxBxHswilh/8xn5MFTKO3Z/g8V43UiUwnu8EE=,iv:iHO4XPw8jpZ6Wi1e4tUbktdB+ZoKwYjCH7vX3r9/8/M=,tag:ixmOlkDt17mfJEhYo1cx7w==,type:str]
    LLDAP_DATABASE_URL: ENC[AES256_GCM,data:bqVgzLF+7SupyvBlpGe8rS0Dg3fXVOl/UoTHQ2NuP2+v3CZ5G5NZRkQxu7wIqFY9avrAfiVWwxiBTsk7GOtR/bzD9t7eNN73Xew0ReOR9CJB+HlUk+nqIFor8RLFm20VK6OLkkbqqWmH44TnvkfyWn3cok7Jbnt9BoXb9czviHLkKnMA,iv:9FjkmMBxGDhb2W1wJY/vHzh26c1Qba7hseZKOVad0nY=,tag:ejbDYxD2TXi/Ra7+io4FVA==,type:str]
    LLDAP_LDAP_BASE_DN: ENC[AES256_GCM,data:qPG3gQM7Ibk3etqv3QY15uY=,iv:RHXARb+bHwwxH+COPFMq9UJ9xqwoCibn6NxdUXXckzA=,tag:Dq7Xg4/kHBSNsdfl5uKS9A==,type:str]
    #ENC[AES256_GCM,data:pyZr/7g=,iv:Sl1+KSo5P7Jy92aXmcS/3SsuzGDZ1dwc7L1FoRqR5SY=,tag:dZPNfZqY88HWNPf8h8q/WA==,type:comment]
    LLDAP_SMTP_OPTIONS_SERVER: ENC[AES256_GCM,data:5jtfumrVok9onZW7OGsJKw==,iv:zv10eMgbbY2SUx1VN/1A6YUXyh407eFloDxj7La9YiI=,tag:J5YCmYxX3lxQVB5XvoFMnA==,type:str]
    LLDAP_SMTP_OPTIONS_PORT: ENC[AES256_GCM,data:NKeg,iv:FzzNDG5XbcQ3CXAzrC8LUUFYexgFqVEnrsfMsCA6ZoQ=,tag:KCkl0PCnvZQItlj9ySUX+A==,type:str]
    LLDAP_SMTP_OPTIONS_USER: ENC[AES256_GCM,data:d8DMZZz6xvcmOaWGTiDY5y5Qm6Q2,iv:yoOmTIueIlzAlZjx9WdzFpY28eVyDhvgqsI0e8P1weQ=,tag:59XXE2o6FGvwMgoINkm9/w==,type:str]
    LLDAP_SMTP_OPTIONS_PASSWORD: ENC[AES256_GCM,data:UsLvE02dpY4VccDNERhUwsPU9A==,iv:3rWvCEZzQxA2QRRy7m1P+in5Us7gtRiB66ERC61V3A4=,tag:rPQYPFlZ0Hn1V2Cv5BiG2A==,type:str]
    LLDAP_SMTP_OPTIONS_FROM: ENC[AES256_GCM,data:gYqOLkyKZTaBHFKerk1gpTF19xu0ZmkJ6RRtHNdV8jh3,iv:t5ilACkwfNH1KA3J/tvl6qMn3tyhOTRATiEKI1Zg3RE=,tag:SmQP8XgdLSDjJiGE2NddYw==,type:str]
    LLDAP_SMTP_OPTIONS_REPLYTO: ENC[AES256_GCM,data:B3qXFrUtyO5ICL0iHyC4kiHTxLF4uQfz2Y5qdWL37T/8OQ==,iv:z2QRQnOphYxH1g5bpiZ1wWsd5Qx0kKrSaV3knb3pqVg=,tag:zaA0LKVRuF5CHLBhR6/xsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dDNFOTJzS0ZWc200SVdG
            cjZmTnJVUUNLRXpEV3pHMGd4cFdVVGYyTVVBClB2WEduMnNBeHdmZk5lYVZvZURn
            OVJTR09aZFpvdnpoQmpUVWdxQUsxcGcKLS0tIGxRcENwN0grMXIwNm5OaGpqQUY5
            dTJuOWdDUG1YQXFERzJKakVCSElnaGMK0ZPB3G21ctfpKtjgjM6mxeA1MljoM9Da
            3RyeysqOeq9DP3ZgKsQOH/O6rbWkeYVfFktlpew/yfzWNX9INy+9kA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T20:39:19Z"
    mac: ENC[AES256_GCM,data:QWfpfRiUl5+8rjybEVIIR690xX/ujWC43AZz/3mXutMEqlYihEWd8gN+7doXvar8cfZuoS/iz2yTTefqonpjP7nwnlLC8ZL7hw2YsLON9R53bssYKT+nnSbfm+nv9e4hNl2HYAR8ztr9F9K7sJdLYqUX3n17jseoK99izSxlx+Y=,iv:upIA6sOLJ3Zw/y+BVWc7biZIH2Lspokg8EWcb9AtL6c=,tag:O8GkTuIVDVLSMC10DFXI0A==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: lldap-dbinit-secret
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:LDyRuTw=,iv:7s5VvvIGglU2mLoRU4m67ThEjwxqV6y82xoVwu2/tfM=,tag:/cicM9ZyZ809wwZSQg4/1w==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:x42dWaMTO5tBjRIifYxfZT1CuZSfxkUNJbxLNPaVmFmTRF5kGpvG6Q==,iv:M+w3567RrBPbQcX1avZv3W1vmLHBZouWZRV0BsrQNSQ=,tag:E8LHj6Pv6BfAJ+zSza2oyA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:ggrth98=,iv:zWUnsrDkpkc89SJVMrYS7302eKeLXJhMwBebk49nS+k=,tag:BdvZwZ0MZVMVmWIiYCjL5g==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Q+gyorz4wtVp0LAFXCpdX/3o5srVJ2KjNL9ViRAQXUzDs4mNcVzGsUEYpJV86b8=,iv:UG8PCFez1w4rNF9EyCiemOVbrmJ76U2zYZhMngIvkKw=,tag:or5WV/Rc8pvgXOo1EnTnSA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:edIZNWxsum53TKkL,iv:cBg1VBGFUzciTtJVjQIBA8Tt40rA1U2tCrGOJiinmGo=,tag:/b2CtTxQ5yW5WkdFavB30g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dDNFOTJzS0ZWc200SVdG
            cjZmTnJVUUNLRXpEV3pHMGd4cFdVVGYyTVVBClB2WEduMnNBeHdmZk5lYVZvZURn
            OVJTR09aZFpvdnpoQmpUVWdxQUsxcGcKLS0tIGxRcENwN0grMXIwNm5OaGpqQUY5
            dTJuOWdDUG1YQXFERzJKakVCSElnaGMK0ZPB3G21ctfpKtjgjM6mxeA1MljoM9Da
            3RyeysqOeq9DP3ZgKsQOH/O6rbWkeYVfFktlpew/yfzWNX9INy+9kA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T20:39:19Z"
    mac: ENC[AES256_GCM,data:QWfpfRiUl5+8rjybEVIIR690xX/ujWC43AZz/3mXutMEqlYihEWd8gN+7doXvar8cfZuoS/iz2yTTefqonpjP7nwnlLC8ZL7hw2YsLON9R53bssYKT+nnSbfm+nv9e4hNl2HYAR8ztr9F9K7sJdLYqUX3n17jseoK99izSxlx+Y=,iv:upIA6sOLJ3Zw/y+BVWc7biZIH2Lspokg8EWcb9AtL6c=,tag:O8GkTuIVDVLSMC10DFXI0A==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.1
