# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: esphome
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: esphome-secret
    template:
      data:
        secrets.yaml: |-
          wifi_ssid: "{{ .ESPHOME_WIFI_SSID }}"
          wifi_password: "{{ .ESPHOME_WIFI_PASSWORD }}"
          api_encryption_key: "{{ .ESPHOME_API_ENCRYPTION_KEY }}"
  dataFrom:
    - extract:
        key: esphome
