apiVersion: v1
kind: Secret
metadata:
    name: teslamate-secret
type: Opaque
data:
    #ENC[AES256_GCM,data:ZNGjKzH2XbgaEA==,iv:hoptp45+UMX57S3YDr6gwHo8w9LC5jW2h/3pHc6fA9U=,tag:TTTShIdeUK7HxlNcOAlp0A==,type:comment]
    MQTT_USERNAME: ENC[AES256_GCM,data:oJKbUygJg50=,iv:/iniQYLoj3Wi3a7e5CSEhDg6TfMUajLQZd7WGxqUxT0=,tag:vc4gUrTnutZyyzZfB1taGg==,type:str]
    MQTT_PASSWORD: ENC[AES256_GCM,data:h5NoQ8sx8Llh8m8s7jG56w==,iv:UdCNSils2MtixQQyRsgSClz9A9L943QDs7rcXz8DXhI=,tag:Y6fKXYYHfsLJOG3Aes/yLg==,type:str]
    DATABASE_HOST: ENC[AES256_GCM,data:1TOMJwL1nVfoPountJUacQrlqHpJm0+Kxvh3U7UQS8RzXDN67NLlUxXloLzfzxklCUFY9MhokaQ=,iv:g+p4WBtO8RkXZb3rEjAJEsMlUOVuu3sv45wqTE6k3Wk=,tag:OWfSc5uGaEEyx26L2nM3zQ==,type:str]
    DATABASE_NAME: ENC[AES256_GCM,data:aiTB3VCx64uVubQX,iv:CUmkPZFIauaKTLhwVSfOmsvG+kz9x01txPVdsZClrnY=,tag:fjZeNwuO4AWS8ViPClVeAQ==,type:str]
    DATABASE_PASS: ENC[AES256_GCM,data:400gSB6hthkG6uLCMRv0Abq87qY3KewlDFhVI1v88rks7/fg8w8iJDasE5rSV+VtqZvXbEunc0KK5A8qDnezcQ==,iv:wwdPaloS0KufAuGlm/POjaaOen0H8BLor+z3rPuJrJo=,tag:woNkPvFD5Q+lMNBuWqt6OA==,type:str]
    DATABASE_USER: ENC[AES256_GCM,data:QSXLPwyWrs8=,iv:lrnR5xo8FcpWqfwcOA2t3Ozn+gZdVeKRGeQNKMopkc0=,tag:qUT2nK/B9XWMewCzsv35DQ==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:b5dysyGYfM0X9gwcIVpt/ODIzCmxmfHr/0MmTvcoMHzbjFF82+lkuQ==,iv:qkDROcuRihlVOE5pPQhmowSa6Eja+u/diFAoENH7F4A=,tag:WYjxrQ7tMUVonKAZDx2WmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQ0pQVmJGVkRpQkF4RXUv
            TDdWYmQ2Wm1MeTVWdTY3L0VOdEUwTitTOEhNCklMeFM4ODNBMVIxNzdGVlBROGE3
            S2QzdDhGcGlZT2FhTk1GVVJCVkZEMVEKLS0tIHc4a294dzF4V3lQeWNhL1RXTkhC
            Q2xvK09aUDNPSWk2MHdCZHh4UXhlQjAK0vNQX4CNyFSskIWu+2Ru2NUjdHEYctGT
            Awmmp6k9LtJVWC7D8LvcybDThg1QHtYJRv5jJ1dI7/T6ofi9H2SKdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T00:07:21Z"
    mac: ENC[AES256_GCM,data:Y1yFTZj/LnQtS/yzhK+uvqBuQ/9iEkO1BckgVuutklws8CsEgAXGYZs6/79O0lQRJiZR6A4YjLJJ3IdtmH7Gdz86v+UqhRT7jEAJT3eZC0V2ZwF5RRVPP8Z3hUzeUc3muaGQfAumhzAqHQZZlOXa8OOV+TXKNFmeJTshOcZmYgA=,iv:oJzqUuoLiOwRu+jivyq678F8At81Efgrh4tPwAgBjyA=,tag:G7atCqVY2KX54myOTpfivA==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: teslamate-dbinit-secret
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:7umqkXuKFb+T1XYI,iv:C9rb54eXy3LpS+5sGAmDv1Hr9tybGJxypyITlsM1muI=,tag:buHyaXa7scdlb0PWTFIICQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:czH12BzndlGg45z6ScUVjMFoqdSZG4rlm7B7qgqBKH8uReoRTkGkcBmzD5QR9koEDtgg+egpOv4=,iv:UpEwmzqTlP58TNdcZs/4kNnv+p0Omxx2vKbU8DMwTKQ=,tag:8b21bRscO5Y8GE7TdLaUjw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:vxJIncp/EHB7jYhBtWfUxvCHKto80e0IqUh+Q/RI7WcJwcjnxygMinnfoKF7REl035+hbCkJhMhDmSq0h2eBmQ==,iv:oezyTFkbiGmLcdXNTyD9y4H0BXL2P1XfBld2tCv2OJg=,tag:7fuR805CFVmJkRgtS07GsA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:/6MKnMMGjgvhZamCMXisvZG3FnET1D/ygFz//qqN+SyjTCSBfeBMcj4RJD/1tY1IWLN+cZ5EVZOybhF9dJ2WHQ==,iv:brGl8MDMHbB+0kJZnI7MpWLtJFlAgaTEH+FQ+46gzVk=,tag:6c3Hx0REZf4Urnz6OHpxow==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:+59Kg63EFII=,iv:uGRhZObzYqNZH/gMkW2jggcaaLVGEwcQRwr6bdNJ5+E=,tag:Bt2HTw8T4IkAn1rmzWyy7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQ0pQVmJGVkRpQkF4RXUv
            TDdWYmQ2Wm1MeTVWdTY3L0VOdEUwTitTOEhNCklMeFM4ODNBMVIxNzdGVlBROGE3
            S2QzdDhGcGlZT2FhTk1GVVJCVkZEMVEKLS0tIHc4a294dzF4V3lQeWNhL1RXTkhC
            Q2xvK09aUDNPSWk2MHdCZHh4UXhlQjAK0vNQX4CNyFSskIWu+2Ru2NUjdHEYctGT
            Awmmp6k9LtJVWC7D8LvcybDThg1QHtYJRv5jJ1dI7/T6ofi9H2SKdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T00:07:21Z"
    mac: ENC[AES256_GCM,data:Y1yFTZj/LnQtS/yzhK+uvqBuQ/9iEkO1BckgVuutklws8CsEgAXGYZs6/79O0lQRJiZR6A4YjLJJ3IdtmH7Gdz86v+UqhRT7jEAJT3eZC0V2ZwF5RRVPP8Z3hUzeUc3muaGQfAumhzAqHQZZlOXa8OOV+TXKNFmeJTshOcZmYgA=,iv:oJzqUuoLiOwRu+jivyq678F8At81Efgrh4tPwAgBjyA=,tag:G7atCqVY2KX54myOTpfivA==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.1
