apiVersion: v1
kind: Secret
metadata:
    name: aws-secret
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:GJU7Tt2FSPkpCsfgTn1CSfEqp30=,iv:m2WfRzf+HYi6XIj7PrO/w3W9IJRlWuc8Ffe913Dmin8=,tag:pnuPBFLmGMQ1q2cgbwzNjQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Ha05KcMm0svaJJO6qUVo4Kq2eFIvtJXY/OAmWm8E0hIe5U5u+u3AhQ==,iv:98NxB8KYk9Alpja2+Zy1eym7h+6zDKJf3wTXLRT0XQA=,tag:+tBCV5ucGqs+GJlpBHGDXA==,type:str]
    URL: ENC[AES256_GCM,data:pDHQ7QgSFmiutCz2sTuqhLsxrvDQ4OWxY7O+hNfb2urPXOKI6/RNfLNlwg==,iv:XCLQ+/396XQHk+UJJlS0XfOeIl1RT9invC4rMWTvF2o=,tag:8Q9sHNBX0Zr+v9aP1XSrNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t8pe6cuxajpqcms5kenlnhh8wmgemr4dnee6eeda07xfsdk2uvtqet3a8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqM0s2cEE0dXh5dE0vZnY3
            V2pabGZqRi95RWpZeEsxWmhxdGliUHo5STJJCkJteUc0cjV6KzlZYzRNazBFdU1j
            M2gyaHFmZVp2TmpLOGlCNUlmS0pkWlkKLS0tIENXeXgxU3h5VS8vUmxsaTdPY0RB
            S3JKNC9mWFRncXNpaTRBM05OR3J3TmMKxPUOc9D29BR6pvYNV5mvoWrzNMdhd/LA
            9bTdtVSbjvYsxlzSdgBv5t6DMzBaWa25Z+nbMDl+ckDCJNG2KQ9+kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T02:56:44Z"
    mac: ENC[AES256_GCM,data:uHgaB1fiv7Dbt1IDfQZfgMpMn5G0e0wS40gsbSZ765RVroaseKINbCG1pYzulcNFV53J/zn39P29D6LuunxS7+E5y5cU8vRcB14arVUBKsxnVFSVmiVszGR8dvo4be8eQ/GsCXe2i+KFL3z35WZ4nIxVNVfRsuiiOo1nUrYxTys=,iv:1EliJz3jL9b66rt4r2A6KAAZYZ4xgfkrhO0ewbPVE2o=,tag:LXu0OGb1q0fPQimFSVvU+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
