apiVersion: v1
kind: Secret
metadata:
    name: longhorn-s3-secret
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:MomElReuy0BTxYWPqvoz2Z0s,iv:OhLr5IDYqopQEJyMEAmxTKUd1Kzkk9mTmz1c0WVOvSs=,tag:YKzFvyW7hENBGowCQwfRhg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:apMQ12xVDytmr1Nu5Ogn1Avn05DwWg==,iv:PGQ7mrXIsKnn/iERX1CCfC2f7rEGpBqgfnBP599fHME=,tag:V/Y6LJeQgxw3NJQFXwY4VQ==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:uyh4iYEi3MxBD2f7oHxdfpAcOyFHzeq15fM/1uwviaW0tJSnad/qhUKxeg==,iv:YtyJ1jdew2kZN4EEEPaI7vG8g7gFwAPlfIGrx6Ms+TI=,tag:BkHoSA9+Lmsp1hpGATipFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t8pe6cuxajpqcms5kenlnhh8wmgemr4dnee6eeda07xfsdk2uvtqet3a8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqM0s2cEE0dXh5dE0vZnY3
            V2pabGZqRi95RWpZeEsxWmhxdGliUHo5STJJCkJteUc0cjV6KzlZYzRNazBFdU1j
            M2gyaHFmZVp2TmpLOGlCNUlmS0pkWlkKLS0tIENXeXgxU3h5VS8vUmxsaTdPY0RB
            S3JKNC9mWFRncXNpaTRBM05OR3J3TmMKxPUOc9D29BR6pvYNV5mvoWrzNMdhd/LA
            9bTdtVSbjvYsxlzSdgBv5t6DMzBaWa25Z+nbMDl+ckDCJNG2KQ9+kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T04:24:03Z"
    mac: ENC[AES256_GCM,data:XIG5DHwVk24idxwgNxI9FlkRxdgjZEK9bgvN5k3xNxoErxYunY+kmjlTU3wolWDXfhZJIx/NLaz7vBjaUSKbaymbxlmz+C/9AbhfdcLx8o4N7+L7jrfjede1j05HKsQa9Dw9LMWN9jHMOMzGE0r2yPoOAPkt7SmjE3KjlY+2zL4=,iv:ahUkB01mhwoyhsBPvpOWVUB1bxh62BlOegKVjyvj4o0=,tag:ibuDO3X5JR6XmYbCnIya3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
