apiVersion: v1
kind: Secret
metadata:
    name: longhorn-s3-secret
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:wAlJGJOGuQHOy0gQ7YG58NcCqL+y5n4ekY74Dw==,iv:EWUxy3LwXxc1T5Do1IudDrpo+bpvJLBg+JkbQ9g7dO0=,tag:1NgAPMTO4fj4036dKj8SLA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:haSNDjKIhivegVH0wL5GbV6H1WkwQlw7SM7Qc7gtu1AMJGb/11mxym3KfEBls8KlSH3ug7Im/k0=,iv:Jhm9HWCY2TZLCWm2CCcXWV/RQOlYp4I8DbJgt/+lkYk=,tag:mRcP+VxrenHXcOK+o/Kt1g==,type:str]
    URL: ENC[AES256_GCM,data:oKRhCRec65SkUlQ088mruhTh6VN8hk5xEcTzUCCDqZ6qPK3N+Ob3A/NITo/8d1X5YCGcPgbi1Rlp3nRh,iv:anZmLlQnjiVlQUNsTyskJ58x2+yRaWZ6/2WTtPIUTII=,tag:vtiGRyy/y1FmcMR3wZwLVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t8pe6cuxajpqcms5kenlnhh8wmgemr4dnee6eeda07xfsdk2uvtqet3a8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqM0s2cEE0dXh5dE0vZnY3
            V2pabGZqRi95RWpZeEsxWmhxdGliUHo5STJJCkJteUc0cjV6KzlZYzRNazBFdU1j
            M2gyaHFmZVp2TmpLOGlCNUlmS0pkWlkKLS0tIENXeXgxU3h5VS8vUmxsaTdPY0RB
            S3JKNC9mWFRncXNpaTRBM05OR3J3TmMKxPUOc9D29BR6pvYNV5mvoWrzNMdhd/LA
            9bTdtVSbjvYsxlzSdgBv5t6DMzBaWa25Z+nbMDl+ckDCJNG2KQ9+kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T03:56:05Z"
    mac: ENC[AES256_GCM,data:6W0nK+VqZOEAAdZZRT1GF7k2RAx1H/3a/5bfxL3S/b7Tk9Mdac3EbowQODIAf4m1Wi5grJyPY/5ohsimKbDv6NzDqlNLGWALtBB8b+siJRPPSg886hvM1FyuFrXeRuHpF3RLRiw/Ptge5EvwCWMxz62V2jIaPE1pCsRIHI5BwCM=,iv:SDoso1Q/hp1lu8odCu0RPJQ5EL6bjvIh857IIPPX9K8=,tag:PdZjMGqCgMEwJTJNQuD+6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
