---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: peanut
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      peanut:
        replicas: 1
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: ghcr.io/brandawg93/peanut
              tag: v3.3.0
            env:
              NUT_HOST: ${PIHOLE_SERVER}
              NUT_PORT: 3493
              WEB_PORT: 8080
            resources:
              requests:
                cpu: 5m
                memory: 32Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true

    service:
      app:
        controller: peanut
        ports:
          http:
            port: 8080

    ingress:
      app:
        className: internal
        annotations:
          external-dns-pihole.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Peanut
          gethomepage.dev/icon: peanut.svg
          gethomepage.dev/group: Home
        hosts:
          - host: peanut.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
