---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted

components:
  - ../../components/sops
  - ../../components/namespace
  - ../../components/netpol

resources:
  - ./actual/ks.yaml
  - ./atuin/ks.yaml
  - ./bambuddy/ks.yaml
  - ./ghostfolio/ks.yaml
  - ./grampsweb/ks.yaml
  - ./lubelog/ks.yaml
  - ./sparkyfitness/ks.yaml
  - ./teslamate/ks.yaml
