---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./database.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
patches:
  - target:
      group: postgresql.cnpg.io
      kind: Cluster
    patch: |-
      - op: add
        path: /spec/postgresql/shared_preload_libraries
        value: [timescaledb]
      - op: add
        path: /spec/postgresql/parameters/timescaledb.license
        value: timescale
      - op: add
        path: /spec/postgresql/parameters/timescaledb.telemetry_level
        value: "off"
      - op: add
        path: /spec/postgresql/extensions
        value:
          - name: timescaledb
            image:
              reference: ghcr.io/inomotech-foss/timescaledb-cnpg:2.28.3-pg18@sha256:33a23e3e4d10ce27e9f69ccd29133be6ae9c6bc19197fb03b9807ac9ae8de92f
