apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: cluster
spec:
  route:
    groupBy: ['alertname', 'app', 'job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 3h
    receiver: 'slack'
    routes:
      - receiver: "null"
        matchers:
          [
            {
              name: alertname,
              value: InfoInhibitor|Watchdog|CPUThrottlingHigh,
              matchType: =~
            }
          ]
      - receiver: slack
        matchers: [{name: severity, value: critical|warning, matchType: =~}]
        continue: true

  receivers:
    - name: "null"
    - name: "slack"
      slackConfigs:
      - apiURL:
          name: alertmanager-secret
          key: slack_url
        channel: '#homelab'
        sendResolved: true
        title: |-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
          {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
            {{" "}}(
            {{- with .CommonLabels.Remove .GroupLabels.Names }}
              {{- range $index, $label := .SortedPairs -}}
                {{ if $index }}, {{ end }}
                {{- $label.Name }}="{{ $label.Value -}}"
              {{- end }}
            {{- end -}}
            )
          {{- end }}
        text: >-
          {{ range .Alerts -}}
          *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

          *Description:* {{ .Annotations.description }}

          *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
