apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:XwIUov2X+ER+53Ob3NcpLZq1WAIEP/kfNQ4tt5/7DIlPHiLQMTcTPPhMChwdav3X+4Jj4d0=,iv:WSlASxu6g70rOEAcPH5qZWwhA0gzy82uQ46I6P6azGI=,tag:tbgxyi0rbYibV3ZiqlsJzg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpb0tSYWcrZW1ucS9Tb1FK
        UVFVc0l5N01vTGF1TC83UzBZY1ZHWkZTY1hvCitWV293SkpyWDVBTDI0Z3AxQm10
        WDdzSTdQN3dvK3BOWjRQRDdaQmtUTkEKLS0tIEZDbGthUUk1NEFEREt3ZkhWV0or
        cnpIK01xZTdrbk1ScDBPZFJUUWxhWE0KCjUBnn2XBdz3Khd0KPHXvdz4uaJ7lvbr
        M4KS/rtMi9MhtNzigNdDsRHsRV5psYSUS/mcoAA+XX2fWnlsVIZDuQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12s85l6vmg08smu66rskhpaupg7htdzdvdrj0ca6rzwn3ujneaq9q7nzaxn
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTWlIYzhydnZUaWptb0ds
        dWdDaDdqY1R5amZVT1Fhb0IxcUs5cEM1cERzCkVmYlBYdThiM2t6QVJxUU1Pbkk5
        UWlMOGNjYWJGMk9Vam83VDlYdjZXRTQKLS0tICtkRkt4L0sxTW9zdWpwdk1uaVR0
        ZXdrTWsxQU9CSFVoWnBlQ1NlVkMvS00KbakT6liq8QPv6DfU1atSytxZqXS9dEfU
        26zTlj63U3Guft3U9P+Rhl2Nqnyomf6f8s6LTvEploA012C6SJueDQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pdy90y7mk4equuwna3eecgl00d8l2max769ym98g54m3lmxjepus5ydsd8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-28T22:15:45Z"
  mac: ENC[AES256_GCM,data:8RaOfPWwSD79z84UdXVlQO9FnYyCmfMVz9Ki+OXWQUgQZeIlGzC33ho+5zwxriGpA6jJYxlB6XVv/sbv838Kefz9V3K+zGqsUqA8JfvG4/8ptScxqZJsDdycReuPWBYZyI6HQw3YMB5QcCFppK56yI/rnZWGYmVXUWRL0lY+3bs=,iv:ohIy68IKdiQ5enrMGTfQUgznAXruEiY93P/2Hbq26e8=,tag:SzGMEiceAzMlIMARAft9lg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
