apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: kube-prometheus-stack
spec:
    chart:
        spec:
            chart: kube-prometheus-stack
            sourceRef:
                kind: HelmRepository
                name: prometheus
            version: 65.3.1
    interval: 1h0m0s
    values:
        crds:
            enabled: false
        prometheus:
            prometheusSpec:
                serviceMonitorSelector:
                    matchLabels: null
                podMonitorSelector:
                    matchLabels: null
                externalUrl: ENC[AES256_GCM,data:8lZzEO5KZ25rehIzMQr5ntVwuF5p2twvsQ51JEBw,iv:3GGdlSCvnB9aIWXW4q9d3mzKGMEMBIgr7MZr+DBhNLo=,tag:Yv3y4CPFsS6JNjxa4NqAAg==,type:str]
                retention: 7d
                storageSpec:
                    volumeClaimTemplate:
                        spec:
                            storageClassName: longhorn
                            accessModes:
                                - ReadWriteOnce
                            resources:
                                requests:
                                    storage: 20Gi
        alertmanager:
            alertmanagerSpec:
                externalUrl: ENC[AES256_GCM,data:8AbXfwF9A0wN5B760a9s4m06kgD1nXxX3/3WO4o49HU=,iv:d2SRgiQlpGTM856bFe5cXvyQ+sGN+FGIWS6RJPTuXU8=,tag:BYi4xFHn4axnSycLRqo7Bw==,type:str]
                retention: 120h
                storage:
                    volumeClaimTemplate:
                        spec:
                            storageClassName: longhorn
                            accessModes:
                                - ReadWriteOnce
                            resources:
                                requests:
                                    storage: 5Gi
        grafana:
            plugins:
                - grafana-piechart-panel
            dashboardProviders:
                dashboardproviders.yaml:
                    apiVersion: 1
                    providers:
                        - name: default
                          orgId: 1
                          folder: ""
                          type: file
                          disableDeletion: false
                          editable: true
                          options:
                            path: /var/lib/grafana/dashboards/default
            dashboards:
                default:
                    node-exporter:
                        gnetId: 11074
                        revision: 9
                        datasource: Prometheus
                    node-exporter-full:
                        gnetId: 1860
                        revision: 37
                        datasource: Prometheus
                    traefik:
                        gnetId: 17347
                        revision: 9
                        datasource: Prometheus
                    flux:
                        gnetId: 16714
                        revision: 1
                        datasource: Prometheus
                    cert-manager:
                        gnetId: 20842
                        revision: 2
                        datasource: Prometheus
                    metallb:
                        gnetId: 20162
                        revision: 5
                        datasource: Prometheus
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQnA5V1AvOWxLeFUxU0tV
            d2dUVm43REtIS2U3ajVaOGsxSGpCbCs0ZUVrCnNtR0ozSDhENmltaDVPb0JYKzlX
            QjVGZEg4bXRwRU83R2FLNk1EUGIrMGsKLS0tIFN3ekdIdTBORTJ2NWNkTnhSV0Vl
            aUpidmEzTDlYd3hDS2l5WEFwb1ZwNDgKKntUdaqO7d9un+1iiP0vSYBqP48bvCZh
            PN6iBcAr/ufKOlBHpD43LLqvnm7H0VMH/8SlBvnfUo1AIfpO3VS5vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-20T19:15:16Z"
    mac: ENC[AES256_GCM,data:2FR1AKWOfZMzyM2MUJcVbjhyOWGcwkrC2RdTTGcHnyf7MCshGMh3SFvxVY60BMomYSDW/41FP7EwRfaDIqbi3Jqfhr2KUsJb/saKve+Eu3Pa2yB2ZA9jeGoH1w04ErD+7MGUmL5NhJU1yrYCshUk1yWH+ZrXV0JIx5IrY9AExTc=,iv:PzlD42l4/UadApESafzpLNkYIBx8BzcoA3nJ2hm3ibE=,tag:LDzQuNHgXuVZUQJioUTRnQ==,type:str]
    pgp: []
    encrypted_regex: ^(externalUrl)$
    version: 3.9.1
