apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: kube-prometheus-stack
spec:
    chart:
        spec:
            chart: kube-prometheus-stack
            sourceRef:
                kind: HelmRepository
                name: prometheus
            version: 65.3.1
    interval: 1h0m0s
    values:
        crds:
            enabled: false
        prometheus:
            prometheusSpec:
                serviceMonitorSelector:
                    matchLabels: null
                podMonitorSelector:
                    matchLabels: null
                externalUrl: ENC[AES256_GCM,data:kkyfNnCYYj8cLGmFFyIabeV/CdNomQNwSugsEX7WRbAfQmHUrI2H,iv:BBGR8VQ4EA1C0n1mwxK4LIpMFm+bHjn7Zh0ltLzwVyo=,tag:vPRKxRKeawW2szFeU/VkCw==,type:str]
                retention: 7d
                storageSpec:
                    volumeClaimTemplate:
                        spec:
                            storageClassName: longhorn
                            accessModes:
                                - ReadWriteOnce
                            resources:
                                requests:
                                    storage: 20Gi
        alertmanager:
            alertmanagerSpec:
                externalUrl: ENC[AES256_GCM,data:B89f+1sjFMXEAzgsoDWELFCn5Qm7kwtZubW7Ar2ocj7hCA/9YvcQLSY=,iv:VWhXCKd1gQc4Q1ltWjm3MSay6tB9+rJCfXDGeUhXWM4=,tag:81LYsTsi1KqLNorKlzL+zw==,type:str]
                retention: 120h
                storage:
                    volumeClaimTemplate:
                        spec:
                            storageClassName: longhorn
                            accessModes:
                                - ReadWriteOnce
                            resources:
                                requests:
                                    storage: 5Gi
        grafana:
            plugins:
                - grafana-piechart-panel
            dashboardProviders:
                dashboardproviders.yaml:
                    apiVersion: 1
                    providers:
                        - name: default
                          orgId: 1
                          folder: ""
                          type: file
                          disableDeletion: false
                          editable: true
                          options:
                            path: /var/lib/grafana/dashboards/default
            dashboards:
                default:
                    node-exporter:
                        gnetId: 11074
                        revision: 9
                        datasource: Prometheus
                    node-exporter-full:
                        gnetId: 1860
                        revision: 37
                        datasource: Prometheus
                    traefik:
                        gnetId: 17347
                        revision: 9
                        datasource: Prometheus
                    flux:
                        gnetId: 16714
                        revision: 1
                        datasource: Prometheus
                    cert-manager:
                        gnetId: 20842
                        revision: 2
                        datasource: Prometheus
                    metallb:
                        gnetId: 20162
                        revision: 5
                        datasource: Prometheus
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTa1Z5RjJMM2U2TWNybjZU
            TUNYRkpST2dtSTR4Q0cyeW55NVZGL1o5bURJCk5mK2EyN2JidmFkMDcwM21aRmZ6
            TVk4QzRFVGVNczhTQjA5ai9ZTE54UFEKLS0tIG9QQjI4N0ZRUXg2RXFmb3dLU3da
            ZlhzT1hEQ25RMDhjYTBkRmZDYjdxOVEK07s1EAPjZxXXXmDkVt9qRmRA1y6dcnzo
            s1VMY6S1irCA/ac+iqLEcFIeHw+pjHfw7Zy1OqJtoh729FuwO2IDxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T21:34:58Z"
    mac: ENC[AES256_GCM,data:P5AmU5MrsJrNtXncRNUJDyaFjG6EtUePz2ivGRfybgfd4iPaePRQA7uqYln7sRIt8ivhk4PxQsagV93u3tHs1huZx29JhAcvvjGTPHpwfVwCuUF2HEF9z32YSZ5CZQb/rqzEaFBeX4TJNcvetX4N/P8NGLSN7wGp7wZ76ch4dpA=,iv:Y+5LzoQHSvkS0TQ+LtbC0Bu5sD5+ki1+Sc60ner8txQ=,tag:X6xubIcVWicQf/kMO4gPhg==,type:str]
    pgp: []
    encrypted_regex: ^(data|externalUrl)$
    version: 3.9.1
