---
access_control:
  default_policy: two_factor

authentication_backend:
  ldap:
    implementation: custom
    address: ldap://lldap.auth.svc.cluster.local:3890
    timeout: 5 seconds
    start_tls: false
    additional_users_dn: ou=people
    users_filter: (&({username_attribute}={input})(objectClass=person))
    additional_groups_dn: ou=groups
    groups_filter: (member={dn})
    group_search_mode: filter
    attributes:
      username: uid
      display_name: displayName
      mail: mail
      group_name: cn

notifier:
  disable_startup_check: false
  smtp:
    subject: '[Authelia] {title}'
    disable_require_tls: false
    disable_starttls: false
    disable_html_emails: false

session:
  name: x_session
  inactivity: 5m
  expiration: 1h
  remember_me: 1M
  cookies:
    - domain: xtmcore.com
      authelia_url: https://auth.xtmcore.com
  redis:
    database_index: 3
    host: dragonfly.database.svc.cluster.local

totp:
  disable: false
  issuer: authelia.com

log:
  level: info
regulation:
  max_retries: 3
  find_time: 1h
  ban_time: 1d

