---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.0-22
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 50Gi
    storageClass: longhorn
  enableSuperuserAccess: true
  superuserSecret:
    name: postgres
  postgresql:
    parameters:
      max_connections: "300"
      shared_buffers: 256MB
  monitoring:
    enablePodMonitor: true
