apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:C0InrfginwIpa+ScEfiUcIcqeYg=,iv:iQOOGlR0cD6rDRCMpmcpqKmwrCVgumMPYvZy/b4JmMY=,tag:6USrRWfKh2EFfBYQfefoUQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:dbo5VmvqdMA+qDf18IinU7Apayob5eBQ,iv:HvFz4zrjoXhTBheJnRaP0obZWtFXOgnLMiEC8CynssY=,tag:VrdmRVG3ymP6FSBd6LQvag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t8pe6cuxajpqcms5kenlnhh8wmgemr4dnee6eeda07xfsdk2uvtqet3a8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZmxxODROMDdrSU5ZdDdG
            NEEvWWg4SzZkRDQ3Rkx4d3JzbWdZbHEwYWswCjRwQ1drbE5CMVNVZnZtUkx3NWJF
            ckVXK3dyWkNGRDZqMDRaSFlGUHlCbmMKLS0tIDZqT28rZzFUMmZFcTlhaW9hRUw0
            dGFydXZCWlFGVFNPVC9HNHEzeFM5YTgKxW/4/ueyCp+HlyKRdKNwX69Y0y/dM8Ov
            Z5RkRnko0C8qgO2jgTgiHTk9x2BwIp1nNEPSJDgySA1YihvWX0Qt8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-31T21:21:41Z"
    mac: ENC[AES256_GCM,data:dMut/YDrGoRVf7OgILKeuaV1fUirdp39uiIYT6buNmeWkFF25VTYLYSLZabZ6hlsWoUDMBpL8PSgkBmpd7mkqWTgf1Jxv2bcKiagU967KCV6xAfoO4g2ALc+2unM5U7/idXIgveD9Q2TuVAT7wYsQEBY91OBv9bXX4GiCyWL5ak=,iv:PFTRPWkRzpPfZZbRrD9dXLwiMRXvRSX6gb5+MHXV4yg=,tag:zn8T/FQTd0w7W+8gCMnFcQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
