apiVersion: v1
kind: Secret
metadata:
    name: external-dns-pihole
stringData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: ENC[AES256_GCM,data:FBoykcdSFPI=,iv:3Ql8TSVY+tyTYLMGcDTGDMjFfpC4dk+9PFkLYcFOWsE=,tag:U6oGCiYcRq/ko2l3prUOwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t8pe6cuxajpqcms5kenlnhh8wmgemr4dnee6eeda07xfsdk2uvtqet3a8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUWUvYWV4dmJCOUJ0Zld4
            cjZHVHRxM01QYklRL01iOEh0OVRCMHAyMEZBCmxWQ0pJcG1FeGhjMnJVWkQxdUFv
            eUVnRGErVlpZOWRZMUtZcm9LbUtmV3cKLS0tIFZRNDQ5WmlkaFZ0Y0F4Z1c1aW5w
            UHpCM3EvSFJCZzU1b2xRTWFsMTdhZ2cKTfIwhyZnXzzPcKU+CS+pXnAJXq2jYJNw
            QoPmCcBk+E5OEMqzjKnqu7ZaohOQ/08mvI3STSpWq0duUYCniSU4hA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-02T04:57:23Z"
    mac: ENC[AES256_GCM,data:Lpsr2g0A/VH9iEqZehVpXB0wFKzNBwft7SsVpVIr///on/mkFClSwBSzhb3g6+dnm/zH9SuHgmrPL8/1s6dkWeotqOn3ex+MVZ9PiCztsNP8Gz+e6j9YgTCBwiTlHWqwsl2g6ljJu8aXQY9GaZbvjbq9BbkvcHfGDO7ryqxaXE4=,iv:AbG2UE4HwGs5kzsfM3k/7dXyY4MxUPYgEr3b9CFQEpk=,tag:Jis7MjwmiRBil/NOxQRLhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
