apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:kUk/WvP9YOKdzPc=,iv:/e1EW+K2Gb9VRYLl4A4i7+UF6laOiwhpUVWxnvVcrUw=,tag:1PEJugJoDDfuaEMDySg8Rg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:IapT5pul7G6loFeXFeMFRwk=,iv:FQNdvLVvjmXHcFabM5vCOlV720DRixsGMUPI0w2S3Fo=,tag:JHbKrvo9MWEE/kXI1rn36A==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:zTQEqqrB1vpp13ENM8Vvb8wZo7hfM0EeQZlugF+o3hUofhNP,iv:aXDKvwq7uDbmZuwtLcLY/L3rWZLipdZ0dwODC7R+OXs=,tag:vFPa/efRt/QUpZr3qeVCtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t8pe6cuxajpqcms5kenlnhh8wmgemr4dnee6eeda07xfsdk2uvtqet3a8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUHYxUGVOdEJGYW5GQnZi
            cFZnQ21uU0Uya1Jpdk5pVnRUTTZuZFhRaFdVClljdExON3VXQyt0S2tacGw3UVFy
            U0duRm9vS3hoSVdNNDEwK2k1VitnUWcKLS0tIEd2SlFhQkg2UzdEK3VJRW1KMnFL
            cVFVYmUvUERsMm5Rb0dyNXIreExYMlkKI/7PdS5irJM/XNoD1DOlNyBZKSbCD323
            gc/NkHr76MyG2qXf/M2ayDU18xJgpFR8dHWkVI6TrdYog9bATHN+0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-28T06:12:38Z"
    mac: ENC[AES256_GCM,data:HWOlLr3qUZI6IlyBwbv0ytjsp/gHwM4sLvIlNXMcZXauuiKnc8LGC9oWyhgxD+0QNUXSYgMEaySXnmd2DaWXC7kxa5y/Q3FEW/gTURXUn92EOAGbqJmzLXHzXLqTi8+ZqF0qv/vBdwj1gHT3+KQaqCN4k/g75VH3pdFX0uk+C+U=,iv:SNQdrF1lZc7b6gZ++a5ZUQK5VDIHwU3XJutnSOgn8cI=,tag:lebvCqzrHcFrB7u5S8a+0g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
