apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: pgadmin
spec:
    chart:
        spec:
            chart: pgadmin4
            sourceRef:
                kind: HelmRepository
                name: runix
            version: 1.31.0
    interval: 1h0m
    values:
        ingress:
            enabled: true
            annotations:
                kubernetes.io/ingress.class: traefik-internal
            hosts:
                - host: ENC[AES256_GCM,data:VPG2imRlut9vb5jdL0Zz/xa+oQ==,iv:60yhKkLWq8QwJS3VvCgROj62zhHSRTvdhIhH+dSWjHA=,tag:3haoUbDB4Gd9lhwBoCbLMA==,type:str]
                  paths:
                    - path: /
                      pathType: Prefix
        env:
            email: ENC[AES256_GCM,data:5fiiWFYzFyqLAkxRnNTWoh+s7bY=,iv:mpy6sKOfflWiHGOqqhLa54D3i6O2FuWAJizyGpy77eM=,tag:6aNCFvrx61ARfR4OpqcDWw==,type:str]
            password: ENC[AES256_GCM,data:OAd1qy2ieMOp3y71L4Kbtn31TapNEHfrmxDhfgtZz5JmSH3R,iv:XbjlgZIfj3U2HoEMHSjvtcB5MzjeraeY0+8tLXI8Nmo=,tag:A+tq0t+B6Wr6FB8SvpAjbw==,type:str]
        persistentVolume:
            enabled: true
            existingClaim: pgadmin-pvc
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRazNNWFJpU2VVVGpDTWpu
            SU55eTQyK0NiRlJpM3phc2FGYlplU005bkRnCjFabDdEZ3YrS0VKa01TUHZHQTVn
            dFZYRW1vb3hlUTVHWHNBMVdUc2pRcEkKLS0tIEpOT3p1MTd6UmphVmpsaC9iZ0oy
            Y1JNUWFVNi9Pb0szY0tmNExUMHg5UnMKApSHYP/mSRmgjogwGXHmLIUiEeKJrALb
            5tAYpVirEt8xag8B9qHRsCkXUYw7lu3EbfbU82CSY3f2v4dL0vwALw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-20T05:15:21Z"
    mac: ENC[AES256_GCM,data:3LOfUbp2mwI7v4TOoevP4NUAZYU6JVjYCf4ZnMrLA4pY/em+MKR58qZT7G6HgZjX4Q/k0DvXQypo4U8AE8uamUJjy2UxHeciX33pcLZ4PNJLwBdoGD/nxqQJhuOI69KPoX4SWa0ObHDPsZahdgWVzjvFDJIkHhNo1yg2yer+dgc=,iv:lgpzMJz9oPdHIWUgwNnBBU4ynToRk+ehWdGaH0yhKcU=,tag:ajs979xGkZ9/Hiho64UUVg==,type:str]
    pgp: []
    encrypted_regex: ^(host|env)$
    version: 3.9.1
