apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: pgadmin
spec:
    chart:
        spec:
            chart: pgadmin4
            sourceRef:
                kind: HelmRepository
                name: runix
            version: 1.31.0
    interval: 1h0m
    values:
        env:
            email: ENC[AES256_GCM,data:5fiiWFYzFyqLAkxRnNTWoh+s7bY=,iv:mpy6sKOfflWiHGOqqhLa54D3i6O2FuWAJizyGpy77eM=,tag:6aNCFvrx61ARfR4OpqcDWw==,type:str]
            password: ENC[AES256_GCM,data:OAd1qy2ieMOp3y71L4Kbtn31TapNEHfrmxDhfgtZz5JmSH3R,iv:XbjlgZIfj3U2HoEMHSjvtcB5MzjeraeY0+8tLXI8Nmo=,tag:A+tq0t+B6Wr6FB8SvpAjbw==,type:str]
        persistentVolume:
            enabled: true
            existingClaim: pgadmin-pvc
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRazNNWFJpU2VVVGpDTWpu
            SU55eTQyK0NiRlJpM3phc2FGYlplU005bkRnCjFabDdEZ3YrS0VKa01TUHZHQTVn
            dFZYRW1vb3hlUTVHWHNBMVdUc2pRcEkKLS0tIEpOT3p1MTd6UmphVmpsaC9iZ0oy
            Y1JNUWFVNi9Pb0szY0tmNExUMHg5UnMKApSHYP/mSRmgjogwGXHmLIUiEeKJrALb
            5tAYpVirEt8xag8B9qHRsCkXUYw7lu3EbfbU82CSY3f2v4dL0vwALw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-20T07:29:33Z"
    mac: ENC[AES256_GCM,data:UF+CywPSza8n0tyV3UQyNkodCl4hpl3JlI0YDWnL4UJvVnv9cD8cLqIdmlFWD9up8sV0GWqpesnp6hwjMASh+8FbPGdRM9p1D2M8w8sqSLWRi3rT7XeEql3d/sDI/kerfVLPNH28O0wXQnWYlEFUm5jJUbJtn7j0pn09eRi94RA=,iv:A0aLy8xPdqI6DiXng9C2MBaHTjcdnjs1LopQR3LjUPM=,tag:IGgRuqjFHmWa1ORI9Y6PIQ==,type:str]
    pgp: []
    encrypted_regex: ^(host|env)$
    version: 3.9.1
