# traefik.containo.us/v1alpha1 depreciated in Traefik v3
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
    name: db-headers
spec:
    headers:
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        referrerPolicy: no-referrer
        contentSecurityPolicy: 'default-src ''none''; script-src ''self'' ''unsafe-inline'' ''unsafe-eval'' https:; style-src ''self'' ''unsafe-inline'' https:; img-src ''self'' data: https:; font-src ''self'' https: data:; connect-src ''self'' https:; frame-src ''self'' https:; media-src ''self'' https:; object-src ''none''; frame-ancestors ''self''; base-uri ''self''; form-action ''self'';'
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
            X-Forwarded-Proto: https
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMjlMczVIRFJyZno2WkJO
            UGVhTFhJY3F1TmJkTXQvSjZIYVVGdFBPZkZnCi9HWlpidXA0WmRweVF3R1h0Sy9M
            K2g3akpLWXo0RC90TS9ZdnJCMVc5OEEKLS0tIGdEcnljYUZvR1B5NE1zWW9XQXln
            VTEyblYyQXV2VTk1cXRVd1JsbElWb2cK4kNeGZP5Vg6RWDKgfCBNoE0ynJV3Pnct
            j+q9l4m/Ox3FLnFi6sAIP+hNNmibHoNgD9UgH200m70MDn2MMXSkRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-20T04:12:30Z"
    mac: ENC[AES256_GCM,data:kx003u6LIQQOedI/MXa4zGPpmPaNrUanoBl6NRHuCYI5oleVtntfSGsz0YL3ggS6pgnpnuR0qaTdFj6ogYeARpDkfdwaN+EjrBeiEB00Cs15ERe/wP7nqSpSqSs9NNH23b0vsTWm7sqjUcUoJONCnmQIePtQjFxDR2eF90zua9Y=,iv:KhY+0lbBKOUV5yhu+jxgsWjOC2X/6cQEYT9l6eDHHnc=,tag:dyMTLOj5bJi4iTJU4jBuXw==,type:str]
    pgp: []
    encrypted_regex: ^(match)$
    version: 3.9.1
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
    name: pgadmin-dashboard
    annotations:
        kubernetes.io/ingress.class: traefik-internal
spec:
    entryPoints:
        - websecure
    routes:
        - match: ENC[AES256_GCM,data:qovQqxs5WHoNIVaOrMokglXO61m2iRlJ+pJ3,iv:LLCwXsK8I9jLNwThCsBoQivDEe//AGHHUhsf1rUrwQo=,tag:R00yAyIyhmTU1Sh1X3JutA==,type:str]
          kind: Rule
          services:
            - name: pgadmin-pgadmin4
              port: 80
              # middlewares:
              #   - name: db-headers
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMjlMczVIRFJyZno2WkJO
            UGVhTFhJY3F1TmJkTXQvSjZIYVVGdFBPZkZnCi9HWlpidXA0WmRweVF3R1h0Sy9M
            K2g3akpLWXo0RC90TS9ZdnJCMVc5OEEKLS0tIGdEcnljYUZvR1B5NE1zWW9XQXln
            VTEyblYyQXV2VTk1cXRVd1JsbElWb2cK4kNeGZP5Vg6RWDKgfCBNoE0ynJV3Pnct
            j+q9l4m/Ox3FLnFi6sAIP+hNNmibHoNgD9UgH200m70MDn2MMXSkRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-20T04:12:30Z"
    mac: ENC[AES256_GCM,data:kx003u6LIQQOedI/MXa4zGPpmPaNrUanoBl6NRHuCYI5oleVtntfSGsz0YL3ggS6pgnpnuR0qaTdFj6ogYeARpDkfdwaN+EjrBeiEB00Cs15ERe/wP7nqSpSqSs9NNH23b0vsTWm7sqjUcUoJONCnmQIePtQjFxDR2eF90zua9Y=,iv:KhY+0lbBKOUV5yhu+jxgsWjOC2X/6cQEYT9l6eDHHnc=,tag:dyMTLOj5bJi4iTJU4jBuXw==,type:str]
    pgp: []
    encrypted_regex: ^(match)$
    version: 3.9.1
