apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pvc
  labels:
    app.kubernetes.io/instance: pgadmin
    app.kubernetes.io/name: pgadmin
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi