apiVersion: v1
type: kubernetes.io/basic-auth
kind: Secret
metadata:
    name: cloudnative-pg-secret
data:
    password: ENC[AES256_GCM,data:F3JJISMbRl8vQoZjO6CASw==,iv:1vX7z77vIQwd52nlvPgzCpMRobDNCV5Tr2jAjiu+IwI=,tag:AabY396VgVMLuqa91FxXUQ==,type:str]
    username: ENC[AES256_GCM,data:Mwn/E66vNqJFKyfR,iv:QD8QxCxSVFbobbHai/DsVvt5vNUglhQgCKewWz9mDeA=,tag:Stq3Amvx7ekFdsEw65baQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDYklGVVVSdnpjYUR0czRS
            eGY2U0FSZW85L0xMenBBbHd6WlI1aFpTTFFFCjBLQk9zWWFnN3d6R2M3UUVidk1s
            cHZ1UjhnWTZ1eHBzY3M3ZFJPVmR3VkEKLS0tIDRtYjBXSjZDckpqaitDRHdkT0lU
            eEt1eHA4U3JaUnd6MXI1MkpzaFNvWEkKhAfVdM0GoaNFpCVWiOm1LdLUNlbtrCa5
            qmf0IPMfLlZ3Xzrx1ZcucTYLPZa2Jg/QnDQFj7Cd6p/KOdqLHQ2wEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-15T04:22:21Z"
    mac: ENC[AES256_GCM,data:FkN5AlK+FAGyDUUlqa0w3t7wc0Mdk3zksS6qmnEReqPTELpJ1Pq8QO1o8LoKfQg3mdzbd7uYoNselJ7p5Ri2N7w59JjFP447ohhoGKjEY09b2doi+/oKzkhFIEkDlCBSM+tk0Pt8EPCtFpwQGgI0+9TIyYAXso4IfH0rPJqkaBA=,iv:ZVgUnbm0ZTmSXbjBIl+4WO2i9k6655QE5f4LOiLj7l8=,tag:WZseJL12+0RcxzdBSIwoHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres16-user
type: kubernetes.io/basic-auth
data:
    password: ENC[AES256_GCM,data:fxxZxZiZbFcTAyrXR9pmcA==,iv:wNrRbA1pl4I3ci95jrlvoCKu7GrTuhHz6DR6Aopds+g=,tag:bvPKs9g5NJe8O+dLworNvA==,type:str]
    username: ENC[AES256_GCM,data:muSiKxAB/mA=,iv:L5YXX7d7/Ck3tMK5yj6KlepSa6TDxPX0LAn2YX/ZGTk=,tag:soz6ZZCA9Um1W5aVZaQClw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDYklGVVVSdnpjYUR0czRS
            eGY2U0FSZW85L0xMenBBbHd6WlI1aFpTTFFFCjBLQk9zWWFnN3d6R2M3UUVidk1s
            cHZ1UjhnWTZ1eHBzY3M3ZFJPVmR3VkEKLS0tIDRtYjBXSjZDckpqaitDRHdkT0lU
            eEt1eHA4U3JaUnd6MXI1MkpzaFNvWEkKhAfVdM0GoaNFpCVWiOm1LdLUNlbtrCa5
            qmf0IPMfLlZ3Xzrx1ZcucTYLPZa2Jg/QnDQFj7Cd6p/KOdqLHQ2wEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-15T04:22:21Z"
    mac: ENC[AES256_GCM,data:FkN5AlK+FAGyDUUlqa0w3t7wc0Mdk3zksS6qmnEReqPTELpJ1Pq8QO1o8LoKfQg3mdzbd7uYoNselJ7p5Ri2N7w59JjFP447ohhoGKjEY09b2doi+/oKzkhFIEkDlCBSM+tk0Pt8EPCtFpwQGgI0+9TIyYAXso4IfH0rPJqkaBA=,iv:ZVgUnbm0ZTmSXbjBIl+4WO2i9k6655QE5f4LOiLj7l8=,tag:WZseJL12+0RcxzdBSIwoHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-s3
type: Opaque
stringData:
    S3_ACCESS_KEY: ENC[AES256_GCM,data:lFEIXkc4A5NzL/MJ8Dhbfp4eF6Q=,iv:CRPAGfQeF5yJlY/ig5oF35bvE1fpgK4ybAVz0o2VlIs=,tag:0/8NbhXK+oypR792yBjKxQ==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:H6GRE/Cqzh1Z169Qo2zN4rLcEIbMMJeMTMpKFeMA+kb94YbG33p0Iw==,iv:uCmIjKDfNo5NwPyNuKgmn88yAqfIvqcUtaoE6dItVRE=,tag:N31X6krT4OaTdZG2MmZqBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDYklGVVVSdnpjYUR0czRS
            eGY2U0FSZW85L0xMenBBbHd6WlI1aFpTTFFFCjBLQk9zWWFnN3d6R2M3UUVidk1s
            cHZ1UjhnWTZ1eHBzY3M3ZFJPVmR3VkEKLS0tIDRtYjBXSjZDckpqaitDRHdkT0lU
            eEt1eHA4U3JaUnd6MXI1MkpzaFNvWEkKhAfVdM0GoaNFpCVWiOm1LdLUNlbtrCa5
            qmf0IPMfLlZ3Xzrx1ZcucTYLPZa2Jg/QnDQFj7Cd6p/KOdqLHQ2wEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-15T04:22:21Z"
    mac: ENC[AES256_GCM,data:FkN5AlK+FAGyDUUlqa0w3t7wc0Mdk3zksS6qmnEReqPTELpJ1Pq8QO1o8LoKfQg3mdzbd7uYoNselJ7p5Ri2N7w59JjFP447ohhoGKjEY09b2doi+/oKzkhFIEkDlCBSM+tk0Pt8EPCtFpwQGgI0+9TIyYAXso4IfH0rPJqkaBA=,iv:ZVgUnbm0ZTmSXbjBIl+4WO2i9k6655QE5f4LOiLj7l8=,tag:WZseJL12+0RcxzdBSIwoHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
