apiVersion: v1
type: kubernetes.io/basic-auth
kind: Secret
metadata:
    name: cloudnative-pg-secret
data:
    password: ENC[AES256_GCM,data:Ob1SRU0gxNSX9eIGxj/XTw==,iv:mvZpi5Z1jWV9oI06QY0hkvLUEzdwbFJG/0PjDRHdR9A=,tag:cXa47iNKV36EbEt0mxs5HA==,type:str]
    username: ENC[AES256_GCM,data:Z/YmyUJAxnrLJ9D8,iv:mMexAFyuOJ9+Fzi/E5iCncp7VR1+D301aTtJJTyOAmc=,tag:bL9O6lfopxmxEfP7qvwqZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCT2xnZmRyRzhWdFEzKzdZ
            cE8wM0JWUTVmMnp6UFlXNzRMQ3RZVHNrL0Y0CjRBczRGeFA0Z1IvZ3Q5WDR5RXhy
            SEV4cU05eFdwN1c5NVJVaVlXdFJZSzAKLS0tIEpreS81UGRUaHg2N0UrODJ3czFD
            RXVtelBBcDVtc0U2ZnBiZmNseUUyZFkKKOCYBjqP8AQgmI//xLJCG8pXI1QPX5aD
            zJ7O+B0akAz7sCjjyzwJkEbfbDHjYbo9+K8tm1ojeW90ODC5x+XD3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T04:00:24Z"
    mac: ENC[AES256_GCM,data:9/2hGAdgvAxA02G1VLHfh9iQZWuptdDO/A8cBPY4YDCuJb+jUSg8/h+trK15u1HTqquyuj+68AKMingggqzwEjl6Bq3D77pFfp6Mc5vs6xj8L1pPqUxs8StxciDm1btSfx77vqVjMzaEWgbY28cMRc3KRphA3Fkg3CLHyC0s3HQ=,iv:KxdeFACnrRK4ecNLzoj2YwsVkgw6IDAwfzo3DfuinxA=,tag:Z0B3K09Obn8zUqY75/G7Qg==,type:str]
    pgp: []
    encrypted_regex: ^(password|username)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres16-user
type: kubernetes.io/basic-auth
data:
    password: ENC[AES256_GCM,data:jOJyh07HybCiVrP+NZo+3A==,iv:S8aI5Y4EB2EYbEOUkiZLBtWBM4UpWJLmwp9wGiv8tMk=,tag:7mG7hG0nKL/6JlqjDOKG9g==,type:str]
    username: ENC[AES256_GCM,data:YWoSN3rgm1s=,iv:9irN4df/lIPuPoiA/xef9pPbeapJWYMj3vw8OSWpY1k=,tag:S3nbUM3/ph2dZDu9MKYaaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCT2xnZmRyRzhWdFEzKzdZ
            cE8wM0JWUTVmMnp6UFlXNzRMQ3RZVHNrL0Y0CjRBczRGeFA0Z1IvZ3Q5WDR5RXhy
            SEV4cU05eFdwN1c5NVJVaVlXdFJZSzAKLS0tIEpreS81UGRUaHg2N0UrODJ3czFD
            RXVtelBBcDVtc0U2ZnBiZmNseUUyZFkKKOCYBjqP8AQgmI//xLJCG8pXI1QPX5aD
            zJ7O+B0akAz7sCjjyzwJkEbfbDHjYbo9+K8tm1ojeW90ODC5x+XD3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T04:00:24Z"
    mac: ENC[AES256_GCM,data:9/2hGAdgvAxA02G1VLHfh9iQZWuptdDO/A8cBPY4YDCuJb+jUSg8/h+trK15u1HTqquyuj+68AKMingggqzwEjl6Bq3D77pFfp6Mc5vs6xj8L1pPqUxs8StxciDm1btSfx77vqVjMzaEWgbY28cMRc3KRphA3Fkg3CLHyC0s3HQ=,iv:KxdeFACnrRK4ecNLzoj2YwsVkgw6IDAwfzo3DfuinxA=,tag:Z0B3K09Obn8zUqY75/G7Qg==,type:str]
    pgp: []
    encrypted_regex: ^(password|username)$
    version: 3.9.1
