apiVersion: v1
kind: Secret
metadata:
    name: gatus-secret
stringData:
    #ENC[AES256_GCM,data:R2jF2jJesYeVr2/77Zo=,iv:VHr9B8ausblWfHpuo2NCAmXot4v9q2pcUkot6No8qjQ=,tag:lA0oK9IFP9Mpu8EkWvByTw==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:f2IFCYo=,iv:PKdIlP+kM59VPFBy2EULZtL8LFNdm/QJZ8wTM0I/2jI=,tag:rcL+F/+/WcpYX+XACaYhJQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:+M3U5IMwJabawqRfplPHdCqsznrHMQqCj6VLMsI7GyOMEcOhhc/Bdg==,iv:NCo6oaB68fPqF6vN1GNp5P0CQIRabrk4sNXf8Kvgms4=,tag:tSZ5edPQJ4eF3is6CQsITQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:pUj2h88=,iv:wYJcpQz+aN7IUAtjrkebBL/vFgE/XBV2jB5c7I16RyQ=,tag:ZiPdA9/v2g/1o6poWY8ntQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:ypaVJJwj6bRradw94GMjhEENfLmNKGritRd5tXYIZuCjNTyouzowD48=,iv:Q9RF5H87tEEHYy5NbNm/UvoQYZG3EyaH2UwMC4Qq1Ro=,tag:NzO1b3Kp5Y+GFOvffaZlYw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:N3ulIx2bO20vWu+3,iv:OCLkmEpZvzXCg3YJGvHrjIrRMht8Z6PzF7//XJn7QNE=,tag:SwwUjWVuqL5klSUNZKZMbA==,type:str]
    #ENC[AES256_GCM,data:Bytzj9WPgxAv2as=,iv:iMPSz1y1V97qDWY1LGqQt50kdRcn1QM3xrqDsG5xUws=,tag:nfT7aIxBcklMIaAo9m2GOw==,type:comment]
    SLACK_WEBHOOK_URL: ENC[AES256_GCM,data:V1eitRHMmT0A1sa2vMShLAAenpG1FkZ1soxbqkWsi6dRAD2H7RoIdMUMTTat2pNwFv5oCsH5ArYD2Ofk/FQtJzjuYOnWM+r+QdxPljlzJ7SG,iv:XaEPlDXClalB9dpIk0V0PCvF/72JVsVfoEBCiIDfcpU=,tag:N1VgP57fNz9Jtg+dukg+pg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SVN3ZHk2aExpM1BNL2Mx
            bHRrUW5kUUxNL2NOMkZwaGhtZ0dFN1RlcGo0ClIyR3hxc2pabit1ZTNGdEN4bHJ1
            QVk2UldKNHc5MlByN3dHdThPR1RNMjAKLS0tIDlQWGFGSHRKVjFHb2VVc1lycmZR
            RUtoNzl5Mkc5SWxLT1FPQzZ4bnNKamMKxlSQrdGJd7Gp7lDrb5KeasrC36hBwYBF
            xsFDuNeTsFZ6dQ0TZaFFk6jPIqklicfewxLfNSIY11Z7YQv1U1fC0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T18:59:38Z"
    mac: ENC[AES256_GCM,data:BodYLkvAtmQS2F6bNFOgvFvjXDTrKVwLR+pOVQ+4rhkGQH+ARJsPdQ0cCkVdTBgDZ5QGyqjqAuqkeff+BFVWgOor9bgzQmT4KxC9PKwWtOzl5ZFngGGsEnnzEMjFqt56o6iawrFXYJdwa2XMHsLLyP5To/Avf/NePe4ZX++exyY=,iv:uk4TbqFE8H7YECOufZm6vwOm+u40UkeQdBkGAvYXiq0=,tag:UJHT9gUzdKYxwX484PibXA==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.1
