apiVersion: v1
kind: Secret
metadata:
    name: gatus-secret
stringData:
    #ENC[AES256_GCM,data:Jomj1TtwmiJHhT57s80=,iv:CkEVTtHOYhoeKqb4McyfckqWxsqKOrhpKKBrhAMiECs=,tag:VZK19DsxOXRZR7I9KBkkrA==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:54nCaew=,iv:EmzCPvRTShtVr4mfQdq9+iPQ7gy7EsGGcCHIPdJgjtc=,tag:HwW1HGAc4LSI6bgbFS8BeA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:LJNYVcw4kKum1Gzi/IttpwnHNbNzAKHuCui/lmvzWT+zdhtr/QF6Ng==,iv:8wA3PKmSmikwdYZhqr20cYWD8GxSQSvcxczXS85n6zs=,tag:H6Nx7GXjcLTR007yBJ78RQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:QU0AIvw=,iv:ivGeO87whSrK7M7GfUCED9stAFevnVlnDkyAI9FIq14=,tag:RBiK4iiMiWx5w4Fbspv5lQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:q+ezS79sfSVfdv6Wc3X5CfO51l7yP3/RCxcffb/cXIYqmqLbEf9JC/Y=,iv:wlXpPWYAsp88jmVs6GRlDyOHGzjg4QUoefqZB/6+uEg=,tag:Hi+mak7n/4S/WWZ4I7/NfA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:gIYlBwMFG4bEeJDg,iv:XnBtz8YXU1G9LlVX9XQXvxzGYKOgaey7jCalOZNe9mU=,tag:KU+etwM4lz4nYBN+Q2z/qg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3OEl0WUd2eVJwNmQ2Y0FH
            ekNDc25ZZ1JxMFlGZDF5TzZSdzlTdEU0MW5JCjdVeFgzemJvOHQyd0lvNTJ3eVFq
            c2xDSHRZSVh1U04ramQycldEeDhjcWsKLS0tIHNraGk5NzhXMjBuK3JLUDlmU3U1
            NHNHVVR1KzlUMnlOaEFqb2QvbXpoNEUKvI9ZpM/scr/9tZ0Db8A8Z2C/QGQCdNZ8
            QZNKjD/I6pRdXVFCLzRflThb3JFZduKhVXRXEVqWub9LyWvi/XSW1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T00:04:58Z"
    mac: ENC[AES256_GCM,data:5DdiyrvYuMTj/tra8cgwbRWBTuVNdsH4oka0cnyITqhL49IQPy4uktuic1oAbCD24VkgB+1HuOLZVuE2g7kvbVhKxe8S9QLz8hx6OsC/RASYvG3jB6uEU/9o1fV8qiiLb7kDxud7uTEkCf0Pd9sEIYuRotz/nZXzDHCPEowwjSY=,iv:Jr2oWwcO0rwxAty7s87o5MPgiTB5l1ZD7tfYoLFC548=,tag:5qI6/l2gUeW1oGQjX79GBw==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.1
