---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gatus
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/monitor/gatus
  prune: true
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/monitor/grafana
  prune: true
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: kube-state-metrics
#   namespace: flux-system
# spec:
#   interval: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./apps/monitor/kube-state-metrics
#   prune: true
#   timeout: 5m
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: kube-prometheus-stack
#   namespace: flux-system
# spec:
#   interval: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./apps/monitor/kube-prometheus-stack
#   prune: true
#   timeout: 5m
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: prometheus-crds
#   namespace: flux-system
# spec:
#   interval: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./infrastructure/kube-prometheus-stack/prometheus-crds
#   prune: true
#   timeout: 5m

# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: kube-prometheus-stack-monitors
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: kube-prometheus-stack
#   interval: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./infrastructure/kube-prometheus-stack/monitors
#   prune: true
#   timeout: 5m
#   decryption:
#     provider: sops
#     secretRef:
#       name: sops-age
