kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: authelia-internal
data:
    jwt_secret: ENC[AES256_GCM,data:jVCVcfOklDhJwpv5TmQnV1Y3E9CTjTcMlc0Cu3jogcDbAAxsb4xrSohxj+3745pqx6ZL7g==,iv:VlK6cUWHWqLdGuE07dTbTLDBBHaAgeZ+HDYtZ2uLBT0=,tag:eeVyDR9G9iCtUehzx2MT4Q==,type:str]
    session_encryption_key: ENC[AES256_GCM,data:hQf4Gz6f96kwswC91Af3n3W0y7/+SRBuj7h0DOfHKWMus18s2FLDDw==,iv:wJOkhjcscT2WplMvHiU/WeB0rdXLLXKfwRW5+oekFfc=,tag:Oi1/Vete0Bm0gwS9Hyu9Zw==,type:str]
    redis_password: ENC[AES256_GCM,data:tQE+KroKTPotwZm1V4ukQQ==,iv:YAuYT3+7hL7GxL969JyJPZ1Be8p1Jh/QX2v6dI5ys74=,tag:zOSVHxcb8Tm3HALE4hhChA==,type:str]
    ldap_password: ENC[AES256_GCM,data:gOWJWzdDjbVfJ8qRfQVyZ0FARNO0rD7KPueL20WPOn5V3EfGZl2YMdCZzGioM8hXtDA6MSjbmADEyrLG8etf4A==,iv:qBBnwpvFoL3lgFfDLa5/e+Le2cVStpnEZkuMPEaQL8M=,tag:YR3+iq7zCkquvv40SZ/5Kg==,type:str]
    psql_password: ENC[AES256_GCM,data:CPVqfRc1vmpzVc/B6bO8LLcwfbCk2MsiGbAwc4m1O+3flwipuSiYJ8BuPEYsvTfY,iv:a494A6TpaOaJNWb92jGdpCiBXsB4iaAPmWtse/Ypda0=,tag:g8mTh5/L9RMYeZnZ0DD2zA==,type:str]
    storage_encryption_key: ENC[AES256_GCM,data:x28EL1+SI8hFAR2SjjBTPV3ciqU451fEhX2oUqRpvq82vcwEVGp2UmXtZKLLLS9XWR7nwcLNyZUlGhOqglmVDdoP6ZdUmKLAfvgtgLlURqC1YLaqLOwvyg==,iv:0svPDh0MIWicKHu1QgmSq5ROw2cLoYNgUNZUadkak0E=,tag:92Me+xoH/MWFLPnPVFqd+w==,type:str]
    smtp_password: ENC[AES256_GCM,data:/slkFhfZohD55V/QtKxeii0smEzoLl1agSdDiA==,iv:P20zCkmgATvGhu5pSUMCuPAHcKllmrOd1PaVASUcHCI=,tag:fSRNBsuDNpmPK3Cbup5M6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRM1N2Nms1a3J4TWFoZmFa
            N3ZkMDl5YlZiWmhIUlZBcm03cnJXNUQrQ0NRCkJJaXRwU0tDR2hNMHlYUEsrME5B
            aFdCRVNPRk9MaHdXRXAybDVxam5kV3cKLS0tIEt6WUJlVlNOM3JIOTFxQTM5K2c2
            Z2grK1lteGNXY3NIcXE4c2pvNk5uUmsKbKuMxyEnWS6ziX5yyTz6sz3oSBfkBJlu
            ERm8zeKjQLD41v4q5llwgVWhUDc6+9KJ0/yzWxK2HW5tCl1IaFnJQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-15T22:27:55Z"
    mac: ENC[AES256_GCM,data:zbp4v4imkCqbPTeAAm0sjhrsV0piSKh246QecL+5zQVKB12uNjokSZ34cxML1/IAeaQKz4zZOmCNLWvsR8E66LpKsuj4l27x6jElQffGFM9s0YpCRlawbPQVebSY1n2UA5fQi3uyX4tREvKTZMN8y5k1gPpktynMNrIIwZ5laW0=,iv:mXmbrAJ1RRmqHpYatCRAOAWJ6oxhq/muIaKTXYLU4Vc=,tag:lsnDwInD9zx/8mHKl1ZMLg==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.1
