# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: home-assistant-secret
    template:
      data:
        id_rsa: "{{ .ADMIN_SSH_PRIVATE_KEY }}"
  dataFrom:
    - extract:
        key: home-assistant
