apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app authelia
spec:
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.5.1
  interval: 1h0m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      authelia:
        enabled: true
        replicas: 3
        strategy: RollingUpdate
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: authelia-secret
        containers:
          app:
            image:
              repository: ghcr.io/authelia/authelia
              tag: 4.38.16
            env:
              TZ: America/Los_Angeles
              AUTHELIA_SERVER_ADDRESS: tcp://0.0.0.0:9091
              AUTHELIA_SERVER_DISABLE_HEALTHCHECK: true
              AUTHELIA_TELEMETRY_METRICS_ADDRESS: tcp://0.0.0.0:8080
              AUTHELIA_TELEMETRY_METRICS_ENABLED: true
              AUTHELIA_DUO_API_DISABLE: true
              AUTHELIA_THEME: dark
              X_AUTHELIA_CONFIG: /config/configuration.yaml
              X_AUTHELIA_CONFIG_FILTERS: expand-env
            envFrom: *envFrom
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: &path /api/health
                    port: &port 9091
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: *app
              
    service:
      app:
        controller: *app
        ports: 
          http:
            port: *port
          metrics:
            enabled: true
            port: 8080
    serviceMonitor:
      app:
        serviceName: *app
        enabled: true
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
    ingress:
      app:
        enabled: true
        className: traefik-external
        annotations:
          gatus.io/path: *path
        hosts:
          - host: &host auth.xtmcore.com
            paths: &paths
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
            - *host

    persistence:
      config:
        type: configMap
        name: authelia-configmap
        globalMounts:
          - path: /config/configuration.yaml
            subPath: configuration.yaml
            readOnly: true

