# traefik.containo.us/v1alpha1 depreciated in Traefik v3
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
    name: auth-ui
    annotations:
        kubernetes.io/ingress.class: traefik-external
spec:
    entryPoints:
        - websecure
    routes:
        - match: ENC[AES256_GCM,data:uslhk2LlZe6vVZlqop7lA93RSRTVSnRX,iv:XEXzRHNfgXyWaGdeoP7AutDEuyPWFPS7drQKzYcJfe4=,tag:E+ix0w0TgI99le4K2IMWwQ==,type:str]
          kind: Rule
          services:
            - name: authelia
              port: 80
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUWpudHRnOGZUU0orVFQv
            ZTZ0M1VtdkhNVDVqTU9qeWhhWVU4ZDBMOFRZCkF4ZGlzTnZPVXdZZVF5SU9tMXVi
            dFQ4RFhLKzlvODVqYnBtcU1Bb1dNT0kKLS0tIHIrb2FUWTdzWUppRHRzWGd0MFMz
            Q29NTTZaMEVySElyRnd1M0laVHVwMWMKTzziEHBdNlfEi3MijauNIB1u7D+VkNi+
            ttNuPnb8soZEr8cb+Yyr2TkKgn8k6Q53b8ijSb2P0uym5CAO0/+rUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-18T02:49:14Z"
    mac: ENC[AES256_GCM,data:IfQuitqoBt2kXt+tP2MmKtvf+jd3iWvMwPdhUW4v3wS/r4pk+oOSROTYhSWtqM43FQYWPTEip4uPGyFFCgB0MIfn1z7ZijmlsRHH9UEKYzDsZOEVSkKLgsJNgv6zImW8Uqfsqr0XIxkPTIH1DEZDtcvbMjqUi5JFDKmZVAAZms8=,iv:JQrf0ai27EdwMVZ3rSgXqICez2Wb5kSFRyl4Glu0kEE=,tag:PXhBIAzR0nXGv1IKHxl+Cw==,type:str]
    pgp: []
    encrypted_regex: ^(match)$
    version: 3.9.1
