apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
    name: auth-ui
    annotations:
        kubernetes.io/ingress.class: traefik-internal
spec:
    entryPoints:
        - websecure
    routes:
        - match: ENC[AES256_GCM,data:H6xtC1ENavFEpJTRLFjuTkjZ4A64zstX,iv:/Fz0NkWj/sP8tie5AxfORJSYz/s6t5ZKSknIhqKS5D4=,tag:q1o6HqDqqIbZeR4gf2yM4g==,type:str]
          kind: Rule
          services:
            - name: authelia
              port: 80
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZStCei9MaHFyRkhsZVlH
            b1p6dEtXYnR4K2V6Q2didXNvVXRjVXlYajFJCndzTWFOSU1CTFNNdUIxNG9DK0px
            NDdWOHZob0laYjNtZzFsTnVJTDFOU1UKLS0tIElUZFVqNjhZOTBIc2NGekNIRlFw
            MlRlOHg2VFBKVWQzaTBXRkVJbFJ4RHcKufynPNdOzkeQxa6Gnrw70dFiBMxdoqIx
            DzEB/yt31y2j+hjbjXL4NNWDQbmqKj6o72CrhMK1nzubZvMi6EGt5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T19:46:44Z"
    mac: ENC[AES256_GCM,data:gfp6/NitckkrGNqGq6XEmC3gFR6vsk4fN0USlmqzbqmfYKc6zdRIQsgTXszGh0O0Tdvdl2lU50lq+gQ2PZ13zB0khZ/vjmiGSwuEE6t+THHzOaKlt9PcNtKUqLioSBsi4umbsixMduUoVDS2/k4Ip98AWnRn9v8Y3FuTeA95aT0=,iv:Acz55GglLdQwbNG0kp1h+ThIi95lLdbo9VcTjbLVEC4=,tag:HHG2e2l3ni6vaVAkvTzSHw==,type:str]
    pgp: []
    encrypted_regex: ^(match)$
    version: 3.9.1
