apiVersion: v1
kind: Secret
metadata:
    name: authelia-secret
stringData:
    #ENC[AES256_GCM,data:X9AsBZYFvD08,iv:VraXdDkrZdOlqrGkxpewxlePDluBpVI6Gyue/SuFCZw=,tag:edGl2YxbBcba7ShqjirGQQ==,type:comment]
    AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: ENC[AES256_GCM,data:OdvWZenz9H/1LQX6AOAtcs2E3Uh9tvUt1BtosI7TMT0Uq1ZBKQ==,iv:OMWov1V8LaGU2VBIcw0DO4i/553MNC4FayyQuHvGGsc=,tag:kGTVMOvx2e9wmv3pzMqjdA==,type:str]
    AUTHELIA_SESSION_SECRET: ENC[AES256_GCM,data:cOq4iCcdbmVoF6VoJDNMw4l9DdLYRRmBrXo2M+g=,iv:o5wGxXv6H5IcOaQLX4QqUPquMnFSQyYQ5XiIAsOz3xo=,tag:f0UaAxwfi2oLI2FP48SUmg==,type:str]
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: ENC[AES256_GCM,data:GfZEOjYgQkXmj1qB+v1Eica2xO7SC8QJIwCwymkAviPsYNnqWuZwpkTRy3k+Wsk=,iv:gIjLwqO3VmqFx30mcxzleYkxKp4ncZyynOtgaXL3UOQ=,tag:F0FxSFTT8ikPAty3BdQ/QA==,type:str]
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USER: ENC[AES256_GCM,data:HVS00ZIDb7yNiZz4m0qLlms1R4AJ2CpwUQV6qgEmMp2hLFou/Q==,iv:qhvCn/NNjz+M2i4N+QkXDVuLboad+jw3v+1/o6l4zHc=,tag:yWwbl7hMVWPLV5OyX41Alg==,type:str]
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_BASE_DN: ENC[AES256_GCM,data:zPiWapgEp5FdisX1z3ZWmck=,iv:d9s8FPtwM9tc842996/h0MY8l2UWzFdpNsoJ5PeqLSo=,tag:659ZdEPirbL6xUZedAFWJg==,type:str]
    AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:wi7/3+pgmDKR9HLDroucysQyI9HxrslL4TyECDo5CNio+7rNsJ6cUuFODk2+dQBGydKR/FIE357A/R9gEGWQs94i60/YCtwSXBKEM8CkF/e1iBc4IAwDXQ==,iv:KRZ8MNv9bwW95uAUUqpKRD0R8XqA0apFuyrNAjeUkeE=,tag:rbRrV2yeb3Tr+RlupybGbg==,type:str]
    AUTHELIA_STORAGE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:V0CYsHTE3ScwpXkzLqZS+jy7kJmYsVfYO2kBVR15ybvHt98=,iv:B4itbNMGZmxthEtKbJO/O+HFvCYUPVc7Tr6HbNjXRn0=,tag:B11+HawNz3+85PD+BC4dpQ==,type:str]
    AUTHELIA_STORAGE_POSTGRES_DATABASE: ENC[AES256_GCM,data:pCh9f2lmSks=,iv:o9LEVKVqefAFvvsk7gph5Fcv5xcQ1Rn2xt/A5XDbX6s=,tag:e5ZXEUyOcFbAoASFVvC6Qg==,type:str]
    AUTHELIA_STORAGE_POSTGRES_ADDRESS: ENC[AES256_GCM,data:hy15wCWadAFBvpkJjSccZh7PeKfJVtY/JeBz0yrBDFP+Uh1U7b0hwA==,iv:P/oxYqWEWIP+xcvMEYzjaco6QcC6+Wtqj1Fe35JepcE=,tag:CV0ZYO6i8FZqjIPKQ1r+6g==,type:str]
    AUTHELIA_STORAGE_POSTGRES_USERNAME: ENC[AES256_GCM,data:K3rXxzU=,iv:cw3byrVamLqhdUBeYvcWx0SJjEv87uUa2bZxlbRIizI=,tag:+g0RVuQV4bVV80PyiGHCmw==,type:str]
    #ENC[AES256_GCM,data:HPCZDyI=,iv:QZvpi+uF9QV01aGzCLHpppbiK12jn25Y5hyDG0oWZAA=,tag:879waIg1Cds0AcU6PlFFGg==,type:comment]
    AUTHELIA_NOTIFIER_SMTP_PASSWORD: ENC[AES256_GCM,data:DvCftC5Ott0UfzurBN/kzIp6lg==,iv:ewozau6QfuubCoCI0fKbRqwICLppIxUhHA3yCeINOR0=,tag:/+SKRF7lB7qOygQBImG7ow==,type:str]
    AUTHELIA_NOTIFIER_SMTP_ADDRESS: ENC[AES256_GCM,data:oxR2zE5Ux4QCNADz2gcfdOchkm0=,iv:G/sJMfuzWqXDUaVQ5lI9OpyakyjiJ8XunS3kgiJCEXI=,tag:XusHzVKURW4d9pwxpU7PFg==,type:str]
    AUTHELIA_NOTIFIER_SMTP_SENDER: ENC[AES256_GCM,data:pb1Zaj9cdpXqzJosNUEKMBDR1ccvkmr2XiBRoSa+aXG3Vrc=,iv:Tfh9qEWjwdeOBqLNsLwXHHdbKxuFVby0SIsDLyqEl1w=,tag:K1winwt+vBtb6uAAJpWqAg==,type:str]
    AUTHELIA_NOTIFIER_SMTP_USERNAME: ENC[AES256_GCM,data:erdr8maPgMnEuSG1JwlTa6uDlDJD,iv:TvE6HmnNxXCn2NszmjGlJ43Oy5TNHN2Eg07hXg7+LTA=,tag:xZ1xMDoSuhG+92dmU6gh7Q==,type:str]
    AUTHELIA_NOTIFIER_SMTP_STARTUP_CHECK_ADDRESS: ENC[AES256_GCM,data:fgbOVQItBFfvB8acMbel4fn2HA==,iv:Y1drIdNM8AbyHKeyaFWaboFQa1e4tAjYeFtKhd1kWw8=,tag:BFPJpojoEwUZCSyLepbykw==,type:str]
    #ENC[AES256_GCM,data:3WoMpr/X6a2vnOPewZ4=,iv:oe+09P83A0JVRfTUSS2Y1ctIUGaJFbWtETRCJ/GYKSk=,tag:8QPC4lOkordTLsOWClt1rw==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:Pg+bjEsB390=,iv:QnN3R25WTMOOZCCPxCc7Z1CPX8gpbxQzdTmnBH9JXY8=,tag:JQhTo/bnDpZ50A4cvfH1FA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:5milZ64fHH9JAvBIgl/lwBocmyljE28+w4c7Rt/vsE5ZhP9WEUJRjg==,iv:alewRoK+1aOoy9ndiR0rknTxvaWMpARvbY367XCvAno=,tag:NCjpCiGSHlnM5wpE4GoRWQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:4gFYwTE=,iv:7niOWWjQyVHx8V20X5FKLbfBkckZi+/UUqsKx+PjfvI=,tag:0F8pcuAFcOBDtT8pXzpjNg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:CD5ypVOOWbIvSjX+i16ow8TUgfzBzn+JbBT8GeS30rFiOt0=,iv:M5VxcbEdVJdbvQSpELQ3wc22xxhJyMNT9Lkyy/cuV7g=,tag:9QMx9uNCTeyCuzqHiin9WQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:vq4i1e7XTH4UAoWs,iv:4WDkQ1OqG64L+nOduQpld5Adv7kgOXnbPnnuJC5OzM8=,tag:f/wi9ZuSuWCNhOYffruFYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxb3h1ZVJ5TUl0SGFrTUVU
            VEZQVUVFWGRWSm5Da1J3bHFoeDNOSVh2OFNBCmZ3cm5uallCbGdER245bWRJNHgx
            STFZeXVHNDBmMFhwS1FhYVBsUFlnKzgKLS0tIFY3bTlCZVZCaDEzd2N1YmJKZ2FD
            bkR4bG9HTERscHhaT1dHTVZRM005YlkK0zN6CW6cdyovD03P56MJfvHbP5V5nBGU
            BFPx0Q0Pw4GDBrWffOfdEDKO36M3lJRCU0tZbD7Qbq2ln+T6VH66zA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-24T23:50:30Z"
    mac: ENC[AES256_GCM,data:mfD4CJN7PLNLZ6XLw6wBD/yk82YS8SXBRR5Bug948RLM/2Skvex6aKZrmBwBPdNIb5RPPpVZEGM2gSKomOZ6ctJF5jKARmC2QCmLkbiW57jEQEmGKrUSJYrel5evvZnyXkc6sf49IPADwidowXHBwbn57kOsZ17vIj07xBCFCJ8=,iv:GipaRcb2r+bHc9GP8svf/nAjirvHWF8BNTMzxxE1BzM=,tag:LyxQk0LCFfqYMKTm/1pElw==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.1
