kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: authelia-secret
data:
    jwt_secret: ENC[AES256_GCM,data:MqVaWJUPWSVD/Po0ddbwacCoNuF+448YqTGX4Id40h8MPmW1ypY7lnzvzi9DjkT/fXmobQ==,iv:GgTehpmMus2mM56OhXX31E0gf/cwkTzZqtpB2kIjkSE=,tag:iNI0usBfTTlWeV23LuEVOg==,type:str]
    session_encryption_key: ENC[AES256_GCM,data:YbT6YX9UDtPs5yIythCerMt9IcniJkjiqQhiwAevO3jBzkFDHUYiTQ==,iv:3TY7BPHQ4zjvPk+Jawp8bn7AizcjOsKjCuzzEbuTCzk=,tag:5K+UBa875UPJ2q40lpOk6w==,type:str]
    redis_password: ENC[AES256_GCM,data:vmT8wjx9VFB6N0qqiWvPvQ==,iv:iuaCg2aQf0P83xxBJBJY5+Z81L25eUVslkbu0/77wZU=,tag:1y3RBNj0fBo/o765lHxCGw==,type:str]
    ldap_password: ENC[AES256_GCM,data:eeg5RsK6O12c6cAV63XwZ03wlllf0UaHmR8qFrkun05kaIwZwCeXzD/01gtO3L2Jwe1eZNHo4GSJ0e9n+LdOjA==,iv:L+DbWJkXsDemoDaPhfCIf1s308Zke7Wo4B/vdo6iZX8=,tag:jx4CcF3f4YFeoyE3XWoQ3Q==,type:str]
    psql_password: ENC[AES256_GCM,data:739wg2Q7d4jA7GvLaFDIXvS0SOMOZzb+Fu3SxvDXZkq/MXMeOqVKdo3Ycfe1DU9/,iv:BJJy/Sup2hAxbYke2sKnYE/wCTFEIA3/6lTS+L/iDMA=,tag:t1pI6YVEJjBINRJuT08nxA==,type:str]
    storage_encryption_key: ENC[AES256_GCM,data:5AeXFFgrurBdj9ovs0vtrLnmCLNWwzVx7lnmT2CjFbREWP6KoWDF9egQaFJa/y1gTNvup9RXY3SiMqYf3GhndGU8845TPdcv+jv7Sc13jk8Pz2DDOASxJA==,iv:xXa+QliQmbV48GtQD38KMt3tJtc6oaxww/mdmgNrGR8=,tag:va5rq7tqwZ1us6cOeAK3iw==,type:str]
    smtp_password: ENC[AES256_GCM,data:pV0/HsC9vsApaZ4HBEj7xqA83WdXaloHMhLB/Q==,iv:5qoiZJVFab9XIZgA2Vecuiu6UXaJ6FuvN/4rKRqgt+o=,tag:75qTXJWiOxwR6BOoVKuxsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bnk0YzRLQVU5eDdrN0ZL
            ekdRZStHTlNuYmlRaWlwQ2lTbTdXbS9rRjBzCjVLU1hHeWpWUUhISUQweTk1ak1v
            R1A4OE5aT1JQNndxUVRZMkFlNjdBck0KLS0tIHlja3l4QTBlK1pLWFZmZkpRc1Jz
            aDU0d09FSlFHWU5ycjBielZJaFhwZzgKZGKEy0mSYU9uPS2qyZ8dUVeyOqertdar
            fnb62TKYp7ISKgUBQekQVNSnwh7qeIFRjnYK4ozqHd/6MgXtYxpweA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-20T03:55:02Z"
    mac: ENC[AES256_GCM,data:KV6MbKFjt3r9v+7XOQhlbweK6wpf4P4LFEiaPgjfMcS8ClS2hOLty3HoLN3i1JChi+iAkTCVAFZtyQlK03B7erG6Jiv4niLHwuNulUaLUcV/60Qq6iTXF/em31Q12g6mlT7QDGnGgRIq4NxG12bP0/KXg6ENdPXz0ehVDXQ4fLc=,iv:PSQrOjOVPH1ersQWw74MG0Xv9pk76YxR0sj7GX3oyuw=,tag:2J7JceNLD825OYICg7ZH6A==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.1
