apiVersion: v1
kind: Secret
metadata:
    name: minio-auth
type: Opaque
stringData:
    USERNAME: ENC[AES256_GCM,data:JP3p3bg=,iv:gaACGbA4dECGq9VIEd61QnERrtXMesIa8y4cd0De2qw=,tag:IKO+++cn8CnSdhMKEgYvaQ==,type:str]
    PASSWORD: ENC[AES256_GCM,data:KP+NKM2w/9456lfThwHdP6g3CTbdSI1INCN6eHj3UwkIwncOm+O955g=,iv:dQPNFCIPKi5iMTH3/5OogZRat0g4dK4HYSO8c77D9y8=,tag:QpyyKx0GdQaTh9/Yjek8Sg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUlNERENreEQrR2E0L0Jp
            dkhrOXRCdUNKd1l3ZVptYUdvU0xJSmxJMkRZCm0zbjU5L1ZFM1gwTnNMWVI4WDE1
            RXZjM2l6RXhYY0FZdXhkVmpDdkdleFUKLS0tIG1oR29ydjhkaW5pNGV4S1VoUWkw
            TmllTUFrdE5YMGZGNmUzNHBLb2ozaVEKK8K4XmENC7XFUVdeqBj3SkN8Oye0TA/d
            gcJPo8YboqyZRFdlVs00D10mfDn8tj/JcSdUIrfFW01iczuUKmAZvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-20T05:45:49Z"
    mac: ENC[AES256_GCM,data:0dEB6laFDl8/lzq6+HeE/xB6fvHyLQ5i2ZRba5Pqcf/bNVJG1eeo3Z+jxsf/Rij8RI5Vr1KRTSm5qYESE3+XsoT2faDfqa4sQj0lODUzNwAS1BNb+8wigOgzYVp7qL2SZgLQrzP24vV+szuu0TP/Ah1mH6Rz7l8JTA+miAVem04=,iv:k14a8XWhkjO9YHG7stFFm9OmwLFzy5EiIPFIYVQ44JQ=,tag:kFFbxAj+ulTb5flKv931sw==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.1
