apiVersion: v1
kind: Secret
metadata:
    name: minio-auth
type: Opaque
stringData:
    USERNAME: ENC[AES256_GCM,data:JP3p3bg=,iv:gaACGbA4dECGq9VIEd61QnERrtXMesIa8y4cd0De2qw=,tag:IKO+++cn8CnSdhMKEgYvaQ==,type:str]
    PASSWORD: ENC[AES256_GCM,data:KP+NKM2w/9456lfThwHdP6g3CTbdSI1INCN6eHj3UwkIwncOm+O955g=,iv:dQPNFCIPKi5iMTH3/5OogZRat0g4dK4HYSO8c77D9y8=,tag:QpyyKx0GdQaTh9/Yjek8Sg==,type:str]
    HOST: ENC[AES256_GCM,data:A/MYNgCyEKU+JuA7m3/COr4=,iv:IhQS14UrpH03pRhu4coMDJMVX39SgO7T4WZmv9VsyT0=,tag:CvXxU1vXHiYh9NqfmMnD7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUlNERENreEQrR2E0L0Jp
            dkhrOXRCdUNKd1l3ZVptYUdvU0xJSmxJMkRZCm0zbjU5L1ZFM1gwTnNMWVI4WDE1
            RXZjM2l6RXhYY0FZdXhkVmpDdkdleFUKLS0tIG1oR29ydjhkaW5pNGV4S1VoUWkw
            TmllTUFrdE5YMGZGNmUzNHBLb2ozaVEKK8K4XmENC7XFUVdeqBj3SkN8Oye0TA/d
            gcJPo8YboqyZRFdlVs00D10mfDn8tj/JcSdUIrfFW01iczuUKmAZvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-20T05:21:20Z"
    mac: ENC[AES256_GCM,data:SqESgmCMSfNifVgALCk31ow3+UlA7RglwaepfqwVD/OfaIBdaHpkaG0dUFVyVqWgQZ06TN9th40uVuIpH3/FtTgw+zVeN7oQtK9EG9+vRavRZLlvsmGb1E/2EgPLDcy3CQJtj1dCjEPkuqQeVhUgDDpqtnnx3rodXYuBKW2p4eg=,iv:dFiOgX6IgyZ6BgHNN1kMpK9GPRHc+PDuVZcod8Z6vk0=,tag:LVgcMLBUuw1FMCNSSesEhg==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.1
