apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
stringData:
    adminuser: ENC[AES256_GCM,data:/Sp9Xdw=,iv:77GY9+Y5Jh3Z9Bui1UsmqvF+JNlL5im5m/p/prRC418=,tag:uXfEp7j40pCw/vrMIbAFJw==,type:str]
    adminPassword: ENC[AES256_GCM,data:rXsBg/soMASw3ViRQ8Mkwvq+CeLF6w==,iv:qkX1wefvJ4c+5qzqXfjYy/uWCXDfwfHWeo+TXU2tKbU=,tag:rXz7iv5DHngNontICfq/mA==,type:str]
    #ENC[AES256_GCM,data:W9fu5knwhxwBMvMP9WCIhCsx3d7YHQs=,iv:8EA10nD9uSi5ERqSa1cZcftKZQAc7XSobHF+xfysTgU=,tag:SinxAhQwqHl41Z3VJb4HjA==,type:comment]
    GF_DATABASE_USER: ENC[AES256_GCM,data:ALKGD3qV,iv:Eyqd8kwSVkwT+cjg638rFIG6HSqiLR/8A3ZX7iUJWus=,tag:1Acu4vH3sjM7qMcn1uASng==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:P3axagfP5WjLN89/j4yc0b8m+LnkqbcXDLhPvFQw2KDFWucUHG8sqrI=,iv:bMytzR1WghDusuY+ehuWSRITDTmTZRqWUM92JmwViYQ=,tag:2NwTOxubA6rBaAMtg4S77g==,type:str]
    GF_DATABASE_HOST: ENC[AES256_GCM,data:C1HCAv8yxonzzIqBR0PMA8juUu84MVHU1Aw+Qouxsn/QxfB+Kel1fw==,iv:n9gkk8nIQJmwvX7YnAUpOPdFuL34Toh9xLW4/ZMIJlE=,tag:gzMXQi/qcNg+hjY9tGgd+A==,type:str]
    GF_DATABASE_NAME: ENC[AES256_GCM,data:G6tPvH2Dtw==,iv:KlYW9gOC4O2lYkwNfPqN/kk+/I4oHjRx56/rFXlVwkM=,tag:FhhnZ16RL2q9+nQ90Zofzw==,type:str]
    GF_DATABASE_SSL_MODE: ENC[AES256_GCM,data:XFKf6zrbEA==,iv:tHACJXbWE2EfH+Ky2OCetEqH7m6Qhygen2dxLBdbIXU=,tag:yDkXrcX8c0JpA8pZSiXndA==,type:str]
    GF_DATABASE_TYPE: ENC[AES256_GCM,data:oRlrQMFmAo4=,iv:M2SWwstZqD1i/mTMkR/PMKZLWlzZMeuGEh/za7tc36Y=,tag:y32RsXPCtuk7CrUnpC4cfw==,type:str]
    #ENC[AES256_GCM,data:aKVJofSUHo4ox2IIF3c=,iv:EgcmxdgS51mxvXksuTgpHRRetCT4towaCVajYbx5wEY=,tag:g+h7JrcvBA7w87vJwOU7WA==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:U3xtX9YDjg==,iv:Y7VIjNfH0zIIOHnEMlMrYgJzpM26YX1sYt0ZpyCm0HE=,tag:g4oOR8WUvnILSdzUJ9cDZQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:y78uIlRLs3w/zTM6iz2fbST9hvHRZ3381B1Gxk0K0VtBUvaq4S1DkQ==,iv:NqE3tysJE1RKEdnmT+fZkEiTrJ2INpG8DHmrWIDNtds=,tag:dfVBvc4omuDokU+q0bL0bw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:jZ53/pkJ,iv:hyTl8dnxTFwMWo+QJpgB7I68YcfUYuJsjZow9jRiHco=,tag:SKnWLbtzwKff5zkVWZBQjQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:1RkdNoIa+uU+Dr86CrzmU0JCUCpryT85pDNjo9hw8bEf3lY5OcmTguY=,iv:cFYIDZFi4xcDipr1B7fdZ3uZKf4XuCkcp1/0gfYlewg=,tag:dq0wttwLUlYb1m5APZfoTw==,type:str]
    INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:TfYrDIkqUfQ=,iv:ALcJ8IGWkk3Og/P1dw+i/VRvGhZpOhYBv2VQ8mdv+JI=,tag:NlOlKlz0ppAFvKIWrj21tw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:FLl8CDG6/zhjVM8q,iv:+OkRx2u0ektD9e/bCoEjH+zQORJS4vbfRcrQ+iQK0B8=,tag:LglbhwTaYuBGUnX5PPziVQ==,type:str]
    #ENC[AES256_GCM,data:N6PVDokfVRVlZ4zO,iv:4qiaKJphQa2st1qu3RaoW3iNs5s9p9CP3FjNpMPusbA=,tag:pmxaFLMlrN9WGVMjl5u3VQ==,type:comment]
    TESLAMATE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:NmqKHJmrKu2zVjh+oMdNHK4s0JyLxWZ5lJMMVM27ykW0r/RFXxyOoLjqo2Ohco4=,iv:eGtflVvzDK/qr0ejS/vbIrgruSulvOgv7pYARwjU7pE=,tag:eHGjMWYVwixGdEewXxIFxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3ehz4v5czfczcmfgnyuc7zmz8pjl055shhek88nsjv2xnrnkq8svjnj5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFc3c2VmZrZUZhRkFnYUIx
            ZWlranNKTktVL1REN0txT1U3QW43SlUzTlRFCmloMTBOK1d1b0Q3azhIY1RScDRV
            dkRnemhubndwMjNkOGVRdEdYaW9WTzQKLS0tIDI3NnRkQUV1ZVNkZGFwdmFVOFVl
            TGRNZGVUeUxIOS81WGI3V09aNEJaT1UK8KbZGp6/7DNc5PCeZO5ZRFTmkEVlqz0j
            nCBMTBBTJV2hPS2QUd/o6rg3ba7oV3Sx40dRPoGmkGz5b7hLDAGNWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T00:02:32Z"
    mac: ENC[AES256_GCM,data:dbfrJJoQYDDzGfLeSEj2jyIs0VIdgIaThWSwDxTOtwHJesg4VVw7AbMTTHgXWKE1tAI3Yg9XrdDInOPgLcXC3AWMX4mV+e68s/9Xu7PXq7/1M9jS/8iaxcFJh+sSG0RpSZ2kaGw88l+jbVVxzMOfKvOd3q9Fq6FySGsCw8+UCwI=,iv:cf05MFHTwKSYJM20QYqIcJrkuH3z8AS6ZTOEtJhWmdY=,tag:U4ENJSVU/uxiFftJCE2QUg==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.1
