---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: changedetection-data
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

