---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-provisioner
  labels:
    kustomize.toolkit.fluxcd.io/substitute: "disabled"
spec:
  interval: 5m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: nfs-provisioner
        namespace: flux-system
      interval: 5m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    replicaCount: 2
    nfs:
      server: "172.16.10.12"
      path: "/volume1/k8s"
      mountOptions:
        - hard
        - nfsvers=4.1
    storageClass:
      create: true
      defaultClass: false
      name: nfs-provision
