# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: pocket-id-secret
    template:
      data:
        ENCRYPTION_KEY: "{{ .ENCRYPTION_KEY }}"
        MAXMIND_LICENSE_KEY: "{{ .MAXMIND_LICENSE_KEY }}"
        # SMTP
        SMTP_HOST: "{{ .SMTP_HOST }}"
        SMTP_PORT: "{{ .SMTP_PORT }}"
        SMTP_FROM: "{{ .SMTP_FROM }}"
        SMTP_USER: "{{ .SMTP_USERNAME }}"
        SMTP_PASSWORD: "{{ .SMTP_PASSWORD }}"
  dataFrom:
    - extract:
        key: pocket-id
    - extract:
        key: maxmind
    - extract:
        key: smtp

