---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Validate

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  manifests:
    name: Validate - Manifests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Mise
        uses: jdx/mise-action@2d8d4cafcbd33be2ea37d2b6f5ad595363d1f1ca # v5.1.1
        with:
          cache: false
          tool_versions: |
            kustomize 5.8.2
            kubeconform 0.8.0
            yq 4.54.1

      - name: Validate Manifests
        run: ./scripts/validate-manifests.sh

  workflows:
    name: Validate - Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Mise
        uses: jdx/mise-action@2d8d4cafcbd33be2ea37d2b6f5ad595363d1f1ca # v5.1.1
        with:
          cache: false
          tool_versions: |
            zizmor 1.30.1

      - name: Run zizmor
        env:
          GH_TOKEN: ${{ github.token }}
        run: zizmor --format plain .github/workflows

  scripts:
    name: Validate - Scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Mise
        uses: jdx/mise-action@2d8d4cafcbd33be2ea37d2b6f5ad595363d1f1ca # v5.1.1
        with:
          cache: false
          tool_versions: |
            shellcheck 0.10.0

      - name: Run shellcheck
        run: shellcheck scripts/*.sh

  success:
    if: ${{ !cancelled() }}
    needs: [manifests, workflows, scripts]
    name: Validate - Success
    runs-on: ubuntu-latest
    steps:
      - name: Any jobs failed?
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

      - name: All jobs passed?
        env:
          RESULTS: ${{ toJSON(needs.*.result) }}
        run: echo "All jobs passed" && echo "$RESULTS"
