---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "${APP}"
spec:
  sourcePVC: "${CLAIM:-${APP}}"
  trigger:
    schedule: "*/30 * * * *"  # every 30 mins
  restic:
    pruneIntervalDays: 14
    repository: "${APP}-restic-secret"
    retain:
      daily: 10
      weekly: 5
      monthly: 3
    copyMethod: "${VOLSYNC_COPYMETHOD:-Snapshot}"
    accessModes: ["${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"]
    storageClassName: "${VOLSYNC_STORAGECLASS:-longhorn}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-longhorn-snapshot}"
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:-5Gi}"

    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:-568}
      runAsGroup: ${VOLSYNC_PGID:-568}
      fsGroup: ${VOLSYNC_PGID:-568}
