---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "${APP}-backup"
spec:
  sourcePVC: "${CLAIM:-${APP}}"
  trigger:
    schedule: "22 * * * *"
  restic:
    pruneIntervalDays: 14
    repository: "${APP}-volsync"
    retain:
      hourly: 24
      daily: 10
      weekly: 5
      monthly: 3
    copyMethod: "${VOLSYNC_COPYMETHOD:-Snapshot}"
    accessModes: ["${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"]
    storageClassName: "${VOLSYNC_STORAGECLASS:-longhorn}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-longhorn-snapshot}"
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:-10Gi}"
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:-longhorn}"
    cacheAccessModes: ["${VOLSYNC_CACHE_ACCESSMODES:-ReadWriteOnce}"]
