apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-restic-secret
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:cBcuGSa5u/c5a5hf02ydyddPs2ivs2LiKdTYI37gQ6gnLd4=,iv:TunMCXlXoqViQyu0D/gHAwNc4L4gdqFcJIT6FU6Q1iI=,tag:hA1VLnLvcFGj8AnsXsznMA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:SOLyCPJWxg5SngFSaZyIE6y+TBSC0R8FlPQ=,iv:2JVzKmp6X9DkZFP/5IwdA026Dnuqh6FxH4SngUJHxUY=,tag:Vm5WAYWs/ySFKzUvB9jUPg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:FhXPl9wtOoI6zQGDLwwsn6cu+aE=,iv:07OZCo0RhvJaoOeDjsjSApdtf0LPC0PgOsqu34456BQ=,tag:rE5R/89o3ZMtRqn66vJnIA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:wTd+/qZLXTCeNF6b9eOWfyDzkwwJKdt8,iv:t8unRu52PHJQDxsnBlhyx+9vrFIviStTsbfr+FBrktQ=,tag:V1GbGHdBn/2sf7eiUOE1lw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t8pe6cuxajpqcms5kenlnhh8wmgemr4dnee6eeda07xfsdk2uvtqet3a8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOHFoRUY0MXpYZlFqbDg4
            a0diK1EyQW9mbzRMaUpCcXAwbUY0WFhuRTAwCmtyVWE0MVErcGFJRjNSYk5tYjly
            dHJFY3JDTDlLNXVsMVhDWWU1QUplZ2cKLS0tIDhPRVdhbytsdFMyblNja1U1bEJM
            dloxQmNLOUhwVkFodFMvbGtZdlJ5T0UKYO2VGztyvdub59wza0Xhh4os4Fl4byn3
            MDHNASOOTc7WNoDrjfnI3bDBflzAT4t23BuTfxp+C+2G2yJXX1Fcxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-31T02:03:54Z"
    mac: ENC[AES256_GCM,data:xO5QwBKhM0sIj3fj1hPQVU1rgylhhoMU/M6ZaybFTNkNr/kBixAaPbzK0jj+cdyjrediZY3hMy5E5GkbU5kGGip6D7S87rEjwVz2rQBqBLzApQuXue8LonWU9aLZMlB56tVKGpfSvjfEplVM7EE0qlItPcDDddNttAf+C3EwLkk=,iv:6DkUkatU+/ukIv3Pc+KLzhkYhxTFfCGPDTwNFZHWU6g=,tag:rwc/1RuCzlTDgAKpD024Rg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
